// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _decoder_2to4_do_decode_HH_
#define _decoder_2to4_do_decode_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct decoder_2to4_do_decode : public sc_module {
    // Port declarations 3
    sc_in< sc_lv<2> > din;
    sc_out< sc_lv<4> > dout;
    sc_out< sc_logic > dout_ap_vld;


    // Module declarations
    decoder_2to4_do_decode(sc_module_name name);
    SC_HAS_PROCESS(decoder_2to4_do_decode);

    ~decoder_2to4_do_decode();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<2> > val_V_read_fu_56_p2;
    static const bool ap_true;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<4> ap_const_lv4_4;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<4> ap_const_lv4_2;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_logic ap_const_logic_0;
    static const sc_logic ap_const_logic_1;
    // Thread declarations
    void thread_dout();
    void thread_dout_ap_vld();
    void thread_val_V_read_fu_56_p2();
};

}

using namespace ap_rtl;

#endif
