// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _decoder_2to4_HH_
#define _decoder_2to4_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "decoder_2to4_do_decode.h"

namespace ap_rtl {

struct decoder_2to4 : public sc_module {
    // Port declarations 2
    sc_in< sc_lv<2> > din;
    sc_out< sc_lv<4> > dout;
    // Internal clock declarations for combination SystemC design. 
    sc_clock ap_sc_inter_clock;


    // Module declarations
    decoder_2to4(sc_module_name name);
    SC_HAS_PROCESS(decoder_2to4);

    ~decoder_2to4();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    decoder_2to4_do_decode* stg_7_decoder_2to4_do_decode_fu_34;
    sc_signal< sc_lv<2> > stg_7_decoder_2to4_do_decode_fu_34_din;
    sc_signal< sc_lv<4> > stg_7_decoder_2to4_do_decode_fu_34_dout;
    sc_signal< sc_logic > stg_7_decoder_2to4_do_decode_fu_34_dout_ap_vld;
    sc_signal< sc_lv<1> > decoder_2to4_ssdm_thread_M_s_load_fu_42_p1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_decoder_2to4_ssdm_thread_M_s_load_fu_42_p1();
    void thread_dout();
    void thread_stg_7_decoder_2to4_do_decode_fu_34_din();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
