-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2015.4
-- Copyright (C) 2015 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mux_4to1 is
port (
    in0 : IN STD_LOGIC;
    in1 : IN STD_LOGIC;
    in2 : IN STD_LOGIC;
    in3 : IN STD_LOGIC;
    sel : IN STD_LOGIC_VECTOR (1 downto 0);
    out_r : OUT STD_LOGIC );
end;


architecture behav of mux_4to1 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "mux_4to1,hls_ip_2015_4,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.877000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=1}";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal stg_11_mux_4to1_process_mux_fu_50_in0 : STD_LOGIC;
    signal stg_11_mux_4to1_process_mux_fu_50_in1 : STD_LOGIC;
    signal stg_11_mux_4to1_process_mux_fu_50_in2 : STD_LOGIC;
    signal stg_11_mux_4to1_process_mux_fu_50_in3 : STD_LOGIC;
    signal stg_11_mux_4to1_process_mux_fu_50_sel : STD_LOGIC_VECTOR (1 downto 0);
    signal stg_11_mux_4to1_process_mux_fu_50_out_r : STD_LOGIC;
    signal stg_11_mux_4to1_process_mux_fu_50_out_r_ap_vld : STD_LOGIC;
    signal mux_4to1_ssdm_thread_M_proc_load_fu_66_p1 : STD_LOGIC_VECTOR (0 downto 0);

    component mux_4to1_process_mux IS
    port (
        in0 : IN STD_LOGIC;
        in1 : IN STD_LOGIC;
        in2 : IN STD_LOGIC;
        in3 : IN STD_LOGIC;
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        out_r : OUT STD_LOGIC;
        out_r_ap_vld : OUT STD_LOGIC );
    end component;



begin
    stg_11_mux_4to1_process_mux_fu_50 : component mux_4to1_process_mux
    port map (
        in0 => stg_11_mux_4to1_process_mux_fu_50_in0,
        in1 => stg_11_mux_4to1_process_mux_fu_50_in1,
        in2 => stg_11_mux_4to1_process_mux_fu_50_in2,
        in3 => stg_11_mux_4to1_process_mux_fu_50_in3,
        sel => stg_11_mux_4to1_process_mux_fu_50_sel,
        out_r => stg_11_mux_4to1_process_mux_fu_50_out_r,
        out_r_ap_vld => stg_11_mux_4to1_process_mux_fu_50_out_r_ap_vld);




    mux_4to1_ssdm_thread_M_proc_load_fu_66_p1 <= ap_const_lv1_0;
    out_r <= stg_11_mux_4to1_process_mux_fu_50_out_r;
    stg_11_mux_4to1_process_mux_fu_50_in0 <= in0;
    stg_11_mux_4to1_process_mux_fu_50_in1 <= in1;
    stg_11_mux_4to1_process_mux_fu_50_in2 <= in2;
    stg_11_mux_4to1_process_mux_fu_50_in3 <= in3;
    stg_11_mux_4to1_process_mux_fu_50_sel <= sel;
end behav;
