// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "mux4bit_4to1_do_mux.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const bool mux4bit_4to1_do_mux::ap_true = true;
const sc_logic mux4bit_4to1_do_mux::ap_const_logic_0 = sc_dt::Log_0;
const sc_logic mux4bit_4to1_do_mux::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<2> mux4bit_4to1_do_mux::ap_const_lv2_3 = "11";
const sc_lv<2> mux4bit_4to1_do_mux::ap_const_lv2_2 = "10";
const sc_lv<2> mux4bit_4to1_do_mux::ap_const_lv2_1 = "1";
const sc_lv<2> mux4bit_4to1_do_mux::ap_const_lv2_0 = "00";
const sc_lv<32> mux4bit_4to1_do_mux::ap_const_lv32_1 = "1";
const sc_lv<32> mux4bit_4to1_do_mux::ap_const_lv32_2 = "10";
const sc_lv<32> mux4bit_4to1_do_mux::ap_const_lv32_3 = "11";
const sc_lv<1> mux4bit_4to1_do_mux::ap_const_lv1_0 = "0";

mux4bit_4to1_do_mux::mux4bit_4to1_do_mux(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_newSel10_fu_453_p3);
    sensitive << ( or_cond3_fu_439_p2 );
    sensitive << ( newSel9_fu_431_p3 );
    sensitive << ( newSel_fu_445_p3 );

    SC_METHOD(thread_newSel1_fu_169_p3);
    sensitive << ( sel_tmp2_fu_129_p2 );
    sensitive << ( tmp_9_fu_109_p1 );
    sensitive << ( sel_tmp1_fu_123_p2 );

    SC_METHOD(thread_newSel2_fu_177_p3);
    sensitive << ( or_cond_fu_163_p2 );
    sensitive << ( tmp_13_fu_155_p3 );
    sensitive << ( newSel1_fu_169_p3 );

    SC_METHOD(thread_newSel3_fu_247_p3);
    sensitive << ( sel_tmp7_fu_241_p2 );
    sensitive << ( tmp_14_fu_185_p3 );
    sensitive << ( tmp_15_fu_193_p3 );

    SC_METHOD(thread_newSel4_fu_261_p3);
    sensitive << ( sel_tmp3_fu_229_p2 );
    sensitive << ( tmp_16_fu_201_p3 );
    sensitive << ( sel_tmp9_fu_223_p2 );

    SC_METHOD(thread_newSel5_fu_269_p3);
    sensitive << ( or_cond1_fu_255_p2 );
    sensitive << ( newSel3_fu_247_p3 );
    sensitive << ( newSel4_fu_261_p3 );

    SC_METHOD(thread_newSel6_fu_339_p3);
    sensitive << ( sel_tmp14_fu_333_p2 );
    sensitive << ( tmp_18_fu_277_p3 );
    sensitive << ( tmp_19_fu_285_p3 );

    SC_METHOD(thread_newSel7_fu_353_p3);
    sensitive << ( sel_tmp12_fu_321_p2 );
    sensitive << ( tmp_20_fu_293_p3 );
    sensitive << ( sel_tmp11_fu_315_p2 );

    SC_METHOD(thread_newSel8_fu_361_p3);
    sensitive << ( or_cond2_fu_347_p2 );
    sensitive << ( newSel6_fu_339_p3 );
    sensitive << ( newSel7_fu_353_p3 );

    SC_METHOD(thread_newSel9_fu_431_p3);
    sensitive << ( sel_tmp19_fu_425_p2 );
    sensitive << ( tmp_22_fu_369_p3 );
    sensitive << ( tmp_23_fu_377_p3 );

    SC_METHOD(thread_newSel_fu_445_p3);
    sensitive << ( sel_tmp17_fu_413_p2 );
    sensitive << ( tmp_24_fu_385_p3 );
    sensitive << ( sel_tmp16_fu_407_p2 );

    SC_METHOD(thread_or_cond1_fu_255_p2);
    sensitive << ( sel_tmp7_fu_241_p2 );
    sensitive << ( sel_tmp5_fu_235_p2 );

    SC_METHOD(thread_or_cond2_fu_347_p2);
    sensitive << ( sel_tmp14_fu_333_p2 );
    sensitive << ( sel_tmp13_fu_327_p2 );

    SC_METHOD(thread_or_cond3_fu_439_p2);
    sensitive << ( sel_tmp19_fu_425_p2 );
    sensitive << ( sel_tmp18_fu_419_p2 );

    SC_METHOD(thread_or_cond_fu_163_p2);
    sensitive << ( sel_tmp6_fu_141_p2 );
    sensitive << ( sel_tmp4_fu_135_p2 );

    SC_METHOD(thread_out_r);
    sensitive << ( newSel10_fu_453_p3 );
    sensitive << ( newSel8_fu_361_p3 );
    sensitive << ( newSel5_fu_269_p3 );
    sensitive << ( newSel2_fu_177_p3 );

    SC_METHOD(thread_out_r_ap_vld);

    SC_METHOD(thread_sel_tmp10_fu_309_p2);
    sensitive << ( sel );
    sensitive << ( sel_tmp12_fu_321_p2 );
    sensitive << ( or_cond2_fu_347_p2 );

    SC_METHOD(thread_sel_tmp11_fu_315_p2);
    sensitive << ( sel_tmp10_fu_309_p2 );
    sensitive << ( tmp_21_fu_301_p3 );

    SC_METHOD(thread_sel_tmp12_fu_321_p2);
    sensitive << ( sel );
    sensitive << ( or_cond2_fu_347_p2 );

    SC_METHOD(thread_sel_tmp13_fu_327_p2);
    sensitive << ( sel );

    SC_METHOD(thread_sel_tmp14_fu_333_p2);
    sensitive << ( sel );

    SC_METHOD(thread_sel_tmp15_fu_401_p2);
    sensitive << ( sel );
    sensitive << ( sel_tmp17_fu_413_p2 );
    sensitive << ( or_cond3_fu_439_p2 );

    SC_METHOD(thread_sel_tmp16_fu_407_p2);
    sensitive << ( sel_tmp15_fu_401_p2 );
    sensitive << ( tmp_25_fu_393_p3 );

    SC_METHOD(thread_sel_tmp17_fu_413_p2);
    sensitive << ( sel );
    sensitive << ( or_cond3_fu_439_p2 );

    SC_METHOD(thread_sel_tmp18_fu_419_p2);
    sensitive << ( sel );

    SC_METHOD(thread_sel_tmp19_fu_425_p2);
    sensitive << ( sel );

    SC_METHOD(thread_sel_tmp1_fu_123_p2);
    sensitive << ( sel_tmp_fu_117_p2 );
    sensitive << ( tmp_10_fu_113_p1 );

    SC_METHOD(thread_sel_tmp2_fu_129_p2);
    sensitive << ( sel );
    sensitive << ( or_cond_fu_163_p2 );

    SC_METHOD(thread_sel_tmp3_fu_229_p2);
    sensitive << ( sel );
    sensitive << ( or_cond1_fu_255_p2 );

    SC_METHOD(thread_sel_tmp4_fu_135_p2);
    sensitive << ( sel );

    SC_METHOD(thread_sel_tmp5_fu_235_p2);
    sensitive << ( sel );

    SC_METHOD(thread_sel_tmp6_fu_141_p2);
    sensitive << ( sel );

    SC_METHOD(thread_sel_tmp7_fu_241_p2);
    sensitive << ( sel );

    SC_METHOD(thread_sel_tmp8_fu_217_p2);
    sensitive << ( sel );
    sensitive << ( sel_tmp3_fu_229_p2 );
    sensitive << ( or_cond1_fu_255_p2 );

    SC_METHOD(thread_sel_tmp9_fu_223_p2);
    sensitive << ( sel_tmp8_fu_217_p2 );
    sensitive << ( tmp_17_fu_209_p3 );

    SC_METHOD(thread_sel_tmp_fu_117_p2);
    sensitive << ( sel );
    sensitive << ( sel_tmp2_fu_129_p2 );
    sensitive << ( or_cond_fu_163_p2 );

    SC_METHOD(thread_tmp_10_fu_113_p1);
    sensitive << ( in3 );

    SC_METHOD(thread_tmp_11_fu_147_p1);
    sensitive << ( in0 );

    SC_METHOD(thread_tmp_12_fu_151_p1);
    sensitive << ( in1 );

    SC_METHOD(thread_tmp_13_fu_155_p3);
    sensitive << ( sel_tmp6_fu_141_p2 );
    sensitive << ( tmp_11_fu_147_p1 );
    sensitive << ( tmp_12_fu_151_p1 );

    SC_METHOD(thread_tmp_14_fu_185_p3);
    sensitive << ( in0 );

    SC_METHOD(thread_tmp_15_fu_193_p3);
    sensitive << ( in1 );

    SC_METHOD(thread_tmp_16_fu_201_p3);
    sensitive << ( in2 );

    SC_METHOD(thread_tmp_17_fu_209_p3);
    sensitive << ( in3 );

    SC_METHOD(thread_tmp_18_fu_277_p3);
    sensitive << ( in0 );

    SC_METHOD(thread_tmp_19_fu_285_p3);
    sensitive << ( in1 );

    SC_METHOD(thread_tmp_20_fu_293_p3);
    sensitive << ( in2 );

    SC_METHOD(thread_tmp_21_fu_301_p3);
    sensitive << ( in3 );

    SC_METHOD(thread_tmp_22_fu_369_p3);
    sensitive << ( in0 );

    SC_METHOD(thread_tmp_23_fu_377_p3);
    sensitive << ( in1 );

    SC_METHOD(thread_tmp_24_fu_385_p3);
    sensitive << ( in2 );

    SC_METHOD(thread_tmp_25_fu_393_p3);
    sensitive << ( in3 );

    SC_METHOD(thread_tmp_9_fu_109_p1);
    sensitive << ( in2 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "mux4bit_4to1_do_mux_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, in0, "(port)in0");
    sc_trace(mVcdFile, in1, "(port)in1");
    sc_trace(mVcdFile, in2, "(port)in2");
    sc_trace(mVcdFile, in3, "(port)in3");
    sc_trace(mVcdFile, sel, "(port)sel");
    sc_trace(mVcdFile, out_r, "(port)out_r");
    sc_trace(mVcdFile, out_r_ap_vld, "(port)out_r_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, sel_tmp_fu_117_p2, "sel_tmp_fu_117_p2");
    sc_trace(mVcdFile, tmp_10_fu_113_p1, "tmp_10_fu_113_p1");
    sc_trace(mVcdFile, sel_tmp6_fu_141_p2, "sel_tmp6_fu_141_p2");
    sc_trace(mVcdFile, tmp_11_fu_147_p1, "tmp_11_fu_147_p1");
    sc_trace(mVcdFile, tmp_12_fu_151_p1, "tmp_12_fu_151_p1");
    sc_trace(mVcdFile, sel_tmp4_fu_135_p2, "sel_tmp4_fu_135_p2");
    sc_trace(mVcdFile, sel_tmp2_fu_129_p2, "sel_tmp2_fu_129_p2");
    sc_trace(mVcdFile, tmp_9_fu_109_p1, "tmp_9_fu_109_p1");
    sc_trace(mVcdFile, sel_tmp1_fu_123_p2, "sel_tmp1_fu_123_p2");
    sc_trace(mVcdFile, or_cond_fu_163_p2, "or_cond_fu_163_p2");
    sc_trace(mVcdFile, tmp_13_fu_155_p3, "tmp_13_fu_155_p3");
    sc_trace(mVcdFile, newSel1_fu_169_p3, "newSel1_fu_169_p3");
    sc_trace(mVcdFile, sel_tmp8_fu_217_p2, "sel_tmp8_fu_217_p2");
    sc_trace(mVcdFile, tmp_17_fu_209_p3, "tmp_17_fu_209_p3");
    sc_trace(mVcdFile, sel_tmp7_fu_241_p2, "sel_tmp7_fu_241_p2");
    sc_trace(mVcdFile, tmp_14_fu_185_p3, "tmp_14_fu_185_p3");
    sc_trace(mVcdFile, tmp_15_fu_193_p3, "tmp_15_fu_193_p3");
    sc_trace(mVcdFile, sel_tmp5_fu_235_p2, "sel_tmp5_fu_235_p2");
    sc_trace(mVcdFile, sel_tmp3_fu_229_p2, "sel_tmp3_fu_229_p2");
    sc_trace(mVcdFile, tmp_16_fu_201_p3, "tmp_16_fu_201_p3");
    sc_trace(mVcdFile, sel_tmp9_fu_223_p2, "sel_tmp9_fu_223_p2");
    sc_trace(mVcdFile, or_cond1_fu_255_p2, "or_cond1_fu_255_p2");
    sc_trace(mVcdFile, newSel3_fu_247_p3, "newSel3_fu_247_p3");
    sc_trace(mVcdFile, newSel4_fu_261_p3, "newSel4_fu_261_p3");
    sc_trace(mVcdFile, sel_tmp10_fu_309_p2, "sel_tmp10_fu_309_p2");
    sc_trace(mVcdFile, tmp_21_fu_301_p3, "tmp_21_fu_301_p3");
    sc_trace(mVcdFile, sel_tmp14_fu_333_p2, "sel_tmp14_fu_333_p2");
    sc_trace(mVcdFile, tmp_18_fu_277_p3, "tmp_18_fu_277_p3");
    sc_trace(mVcdFile, tmp_19_fu_285_p3, "tmp_19_fu_285_p3");
    sc_trace(mVcdFile, sel_tmp13_fu_327_p2, "sel_tmp13_fu_327_p2");
    sc_trace(mVcdFile, sel_tmp12_fu_321_p2, "sel_tmp12_fu_321_p2");
    sc_trace(mVcdFile, tmp_20_fu_293_p3, "tmp_20_fu_293_p3");
    sc_trace(mVcdFile, sel_tmp11_fu_315_p2, "sel_tmp11_fu_315_p2");
    sc_trace(mVcdFile, or_cond2_fu_347_p2, "or_cond2_fu_347_p2");
    sc_trace(mVcdFile, newSel6_fu_339_p3, "newSel6_fu_339_p3");
    sc_trace(mVcdFile, newSel7_fu_353_p3, "newSel7_fu_353_p3");
    sc_trace(mVcdFile, sel_tmp15_fu_401_p2, "sel_tmp15_fu_401_p2");
    sc_trace(mVcdFile, tmp_25_fu_393_p3, "tmp_25_fu_393_p3");
    sc_trace(mVcdFile, sel_tmp19_fu_425_p2, "sel_tmp19_fu_425_p2");
    sc_trace(mVcdFile, tmp_22_fu_369_p3, "tmp_22_fu_369_p3");
    sc_trace(mVcdFile, tmp_23_fu_377_p3, "tmp_23_fu_377_p3");
    sc_trace(mVcdFile, sel_tmp18_fu_419_p2, "sel_tmp18_fu_419_p2");
    sc_trace(mVcdFile, sel_tmp17_fu_413_p2, "sel_tmp17_fu_413_p2");
    sc_trace(mVcdFile, tmp_24_fu_385_p3, "tmp_24_fu_385_p3");
    sc_trace(mVcdFile, sel_tmp16_fu_407_p2, "sel_tmp16_fu_407_p2");
    sc_trace(mVcdFile, or_cond3_fu_439_p2, "or_cond3_fu_439_p2");
    sc_trace(mVcdFile, newSel9_fu_431_p3, "newSel9_fu_431_p3");
    sc_trace(mVcdFile, newSel_fu_445_p3, "newSel_fu_445_p3");
    sc_trace(mVcdFile, newSel10_fu_453_p3, "newSel10_fu_453_p3");
    sc_trace(mVcdFile, newSel8_fu_361_p3, "newSel8_fu_361_p3");
    sc_trace(mVcdFile, newSel5_fu_269_p3, "newSel5_fu_269_p3");
    sc_trace(mVcdFile, newSel2_fu_177_p3, "newSel2_fu_177_p3");
#endif

    }
}

mux4bit_4to1_do_mux::~mux4bit_4to1_do_mux() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void mux4bit_4to1_do_mux::thread_newSel10_fu_453_p3() {
    newSel10_fu_453_p3 = (!or_cond3_fu_439_p2.read()[0].is_01())? sc_lv<1>(): ((or_cond3_fu_439_p2.read()[0].to_bool())? newSel9_fu_431_p3.read(): newSel_fu_445_p3.read());
}

void mux4bit_4to1_do_mux::thread_newSel1_fu_169_p3() {
    newSel1_fu_169_p3 = (!sel_tmp2_fu_129_p2.read()[0].is_01())? sc_lv<1>(): ((sel_tmp2_fu_129_p2.read()[0].to_bool())? tmp_9_fu_109_p1.read(): sel_tmp1_fu_123_p2.read());
}

void mux4bit_4to1_do_mux::thread_newSel2_fu_177_p3() {
    newSel2_fu_177_p3 = (!or_cond_fu_163_p2.read()[0].is_01())? sc_lv<1>(): ((or_cond_fu_163_p2.read()[0].to_bool())? tmp_13_fu_155_p3.read(): newSel1_fu_169_p3.read());
}

void mux4bit_4to1_do_mux::thread_newSel3_fu_247_p3() {
    newSel3_fu_247_p3 = (!sel_tmp7_fu_241_p2.read()[0].is_01())? sc_lv<1>(): ((sel_tmp7_fu_241_p2.read()[0].to_bool())? tmp_14_fu_185_p3.read(): tmp_15_fu_193_p3.read());
}

void mux4bit_4to1_do_mux::thread_newSel4_fu_261_p3() {
    newSel4_fu_261_p3 = (!sel_tmp3_fu_229_p2.read()[0].is_01())? sc_lv<1>(): ((sel_tmp3_fu_229_p2.read()[0].to_bool())? tmp_16_fu_201_p3.read(): sel_tmp9_fu_223_p2.read());
}

void mux4bit_4to1_do_mux::thread_newSel5_fu_269_p3() {
    newSel5_fu_269_p3 = (!or_cond1_fu_255_p2.read()[0].is_01())? sc_lv<1>(): ((or_cond1_fu_255_p2.read()[0].to_bool())? newSel3_fu_247_p3.read(): newSel4_fu_261_p3.read());
}

void mux4bit_4to1_do_mux::thread_newSel6_fu_339_p3() {
    newSel6_fu_339_p3 = (!sel_tmp14_fu_333_p2.read()[0].is_01())? sc_lv<1>(): ((sel_tmp14_fu_333_p2.read()[0].to_bool())? tmp_18_fu_277_p3.read(): tmp_19_fu_285_p3.read());
}

void mux4bit_4to1_do_mux::thread_newSel7_fu_353_p3() {
    newSel7_fu_353_p3 = (!sel_tmp12_fu_321_p2.read()[0].is_01())? sc_lv<1>(): ((sel_tmp12_fu_321_p2.read()[0].to_bool())? tmp_20_fu_293_p3.read(): sel_tmp11_fu_315_p2.read());
}

void mux4bit_4to1_do_mux::thread_newSel8_fu_361_p3() {
    newSel8_fu_361_p3 = (!or_cond2_fu_347_p2.read()[0].is_01())? sc_lv<1>(): ((or_cond2_fu_347_p2.read()[0].to_bool())? newSel6_fu_339_p3.read(): newSel7_fu_353_p3.read());
}

void mux4bit_4to1_do_mux::thread_newSel9_fu_431_p3() {
    newSel9_fu_431_p3 = (!sel_tmp19_fu_425_p2.read()[0].is_01())? sc_lv<1>(): ((sel_tmp19_fu_425_p2.read()[0].to_bool())? tmp_22_fu_369_p3.read(): tmp_23_fu_377_p3.read());
}

void mux4bit_4to1_do_mux::thread_newSel_fu_445_p3() {
    newSel_fu_445_p3 = (!sel_tmp17_fu_413_p2.read()[0].is_01())? sc_lv<1>(): ((sel_tmp17_fu_413_p2.read()[0].to_bool())? tmp_24_fu_385_p3.read(): sel_tmp16_fu_407_p2.read());
}

void mux4bit_4to1_do_mux::thread_or_cond1_fu_255_p2() {
    or_cond1_fu_255_p2 = (sel_tmp7_fu_241_p2.read() | sel_tmp5_fu_235_p2.read());
}

void mux4bit_4to1_do_mux::thread_or_cond2_fu_347_p2() {
    or_cond2_fu_347_p2 = (sel_tmp14_fu_333_p2.read() | sel_tmp13_fu_327_p2.read());
}

void mux4bit_4to1_do_mux::thread_or_cond3_fu_439_p2() {
    or_cond3_fu_439_p2 = (sel_tmp19_fu_425_p2.read() | sel_tmp18_fu_419_p2.read());
}

void mux4bit_4to1_do_mux::thread_or_cond_fu_163_p2() {
    or_cond_fu_163_p2 = (sel_tmp6_fu_141_p2.read() | sel_tmp4_fu_135_p2.read());
}

void mux4bit_4to1_do_mux::thread_out_r() {
    out_r = esl_concat<3,1>(esl_concat<2,1>(esl_concat<1,1>(newSel10_fu_453_p3.read(), newSel8_fu_361_p3.read()), newSel5_fu_269_p3.read()), newSel2_fu_177_p3.read());
}

void mux4bit_4to1_do_mux::thread_out_r_ap_vld() {
    if (esl_seteq<1,1,1>(ap_true, ap_true)) {
        out_r_ap_vld = ap_const_logic_1;
    } else {
        out_r_ap_vld = ap_const_logic_0;
    }
}

void mux4bit_4to1_do_mux::thread_sel_tmp10_fu_309_p2() {
    sel_tmp10_fu_309_p2 = (!sel.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(sel.read() == ap_const_lv2_3);
}

void mux4bit_4to1_do_mux::thread_sel_tmp11_fu_315_p2() {
    sel_tmp11_fu_315_p2 = (sel_tmp10_fu_309_p2.read() & tmp_21_fu_301_p3.read());
}

void mux4bit_4to1_do_mux::thread_sel_tmp12_fu_321_p2() {
    sel_tmp12_fu_321_p2 = (!sel.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(sel.read() == ap_const_lv2_2);
}

void mux4bit_4to1_do_mux::thread_sel_tmp13_fu_327_p2() {
    sel_tmp13_fu_327_p2 = (!sel.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(sel.read() == ap_const_lv2_1);
}

void mux4bit_4to1_do_mux::thread_sel_tmp14_fu_333_p2() {
    sel_tmp14_fu_333_p2 = (!sel.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(sel.read() == ap_const_lv2_0);
}

void mux4bit_4to1_do_mux::thread_sel_tmp15_fu_401_p2() {
    sel_tmp15_fu_401_p2 = (!sel.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(sel.read() == ap_const_lv2_3);
}

void mux4bit_4to1_do_mux::thread_sel_tmp16_fu_407_p2() {
    sel_tmp16_fu_407_p2 = (sel_tmp15_fu_401_p2.read() & tmp_25_fu_393_p3.read());
}

void mux4bit_4to1_do_mux::thread_sel_tmp17_fu_413_p2() {
    sel_tmp17_fu_413_p2 = (!sel.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(sel.read() == ap_const_lv2_2);
}

void mux4bit_4to1_do_mux::thread_sel_tmp18_fu_419_p2() {
    sel_tmp18_fu_419_p2 = (!sel.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(sel.read() == ap_const_lv2_1);
}

void mux4bit_4to1_do_mux::thread_sel_tmp19_fu_425_p2() {
    sel_tmp19_fu_425_p2 = (!sel.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(sel.read() == ap_const_lv2_0);
}

void mux4bit_4to1_do_mux::thread_sel_tmp1_fu_123_p2() {
    sel_tmp1_fu_123_p2 = (sel_tmp_fu_117_p2.read() & tmp_10_fu_113_p1.read());
}

void mux4bit_4to1_do_mux::thread_sel_tmp2_fu_129_p2() {
    sel_tmp2_fu_129_p2 = (!sel.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(sel.read() == ap_const_lv2_2);
}

void mux4bit_4to1_do_mux::thread_sel_tmp3_fu_229_p2() {
    sel_tmp3_fu_229_p2 = (!sel.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(sel.read() == ap_const_lv2_2);
}

void mux4bit_4to1_do_mux::thread_sel_tmp4_fu_135_p2() {
    sel_tmp4_fu_135_p2 = (!sel.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(sel.read() == ap_const_lv2_1);
}

void mux4bit_4to1_do_mux::thread_sel_tmp5_fu_235_p2() {
    sel_tmp5_fu_235_p2 = (!sel.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(sel.read() == ap_const_lv2_1);
}

void mux4bit_4to1_do_mux::thread_sel_tmp6_fu_141_p2() {
    sel_tmp6_fu_141_p2 = (!sel.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(sel.read() == ap_const_lv2_0);
}

void mux4bit_4to1_do_mux::thread_sel_tmp7_fu_241_p2() {
    sel_tmp7_fu_241_p2 = (!sel.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(sel.read() == ap_const_lv2_0);
}

void mux4bit_4to1_do_mux::thread_sel_tmp8_fu_217_p2() {
    sel_tmp8_fu_217_p2 = (!sel.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(sel.read() == ap_const_lv2_3);
}

void mux4bit_4to1_do_mux::thread_sel_tmp9_fu_223_p2() {
    sel_tmp9_fu_223_p2 = (sel_tmp8_fu_217_p2.read() & tmp_17_fu_209_p3.read());
}

void mux4bit_4to1_do_mux::thread_sel_tmp_fu_117_p2() {
    sel_tmp_fu_117_p2 = (!sel.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(sel.read() == ap_const_lv2_3);
}

void mux4bit_4to1_do_mux::thread_tmp_10_fu_113_p1() {
    tmp_10_fu_113_p1 = in3.read().range(1-1, 0);
}

void mux4bit_4to1_do_mux::thread_tmp_11_fu_147_p1() {
    tmp_11_fu_147_p1 = in0.read().range(1-1, 0);
}

void mux4bit_4to1_do_mux::thread_tmp_12_fu_151_p1() {
    tmp_12_fu_151_p1 = in1.read().range(1-1, 0);
}

void mux4bit_4to1_do_mux::thread_tmp_13_fu_155_p3() {
    tmp_13_fu_155_p3 = (!sel_tmp6_fu_141_p2.read()[0].is_01())? sc_lv<1>(): ((sel_tmp6_fu_141_p2.read()[0].to_bool())? tmp_11_fu_147_p1.read(): tmp_12_fu_151_p1.read());
}

void mux4bit_4to1_do_mux::thread_tmp_14_fu_185_p3() {
    tmp_14_fu_185_p3 = in0.read().range(1, 1);
}

void mux4bit_4to1_do_mux::thread_tmp_15_fu_193_p3() {
    tmp_15_fu_193_p3 = in1.read().range(1, 1);
}

void mux4bit_4to1_do_mux::thread_tmp_16_fu_201_p3() {
    tmp_16_fu_201_p3 = in2.read().range(1, 1);
}

void mux4bit_4to1_do_mux::thread_tmp_17_fu_209_p3() {
    tmp_17_fu_209_p3 = in3.read().range(1, 1);
}

void mux4bit_4to1_do_mux::thread_tmp_18_fu_277_p3() {
    tmp_18_fu_277_p3 = in0.read().range(2, 2);
}

void mux4bit_4to1_do_mux::thread_tmp_19_fu_285_p3() {
    tmp_19_fu_285_p3 = in1.read().range(2, 2);
}

void mux4bit_4to1_do_mux::thread_tmp_20_fu_293_p3() {
    tmp_20_fu_293_p3 = in2.read().range(2, 2);
}

void mux4bit_4to1_do_mux::thread_tmp_21_fu_301_p3() {
    tmp_21_fu_301_p3 = in3.read().range(2, 2);
}

void mux4bit_4to1_do_mux::thread_tmp_22_fu_369_p3() {
    tmp_22_fu_369_p3 = in0.read().range(3, 3);
}

void mux4bit_4to1_do_mux::thread_tmp_23_fu_377_p3() {
    tmp_23_fu_377_p3 = in1.read().range(3, 3);
}

void mux4bit_4to1_do_mux::thread_tmp_24_fu_385_p3() {
    tmp_24_fu_385_p3 = in2.read().range(3, 3);
}

void mux4bit_4to1_do_mux::thread_tmp_25_fu_393_p3() {
    tmp_25_fu_393_p3 = in3.read().range(3, 3);
}

void mux4bit_4to1_do_mux::thread_tmp_9_fu_109_p1() {
    tmp_9_fu_109_p1 = in2.read().range(1-1, 0);
}

}

