// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _mux4bit_4to1_do_mux_HH_
#define _mux4bit_4to1_do_mux_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct mux4bit_4to1_do_mux : public sc_module {
    // Port declarations 7
    sc_in< sc_lv<4> > in0;
    sc_in< sc_lv<4> > in1;
    sc_in< sc_lv<4> > in2;
    sc_in< sc_lv<4> > in3;
    sc_in< sc_lv<2> > sel;
    sc_out< sc_lv<4> > out_r;
    sc_out< sc_logic > out_r_ap_vld;


    // Module declarations
    mux4bit_4to1_do_mux(sc_module_name name);
    SC_HAS_PROCESS(mux4bit_4to1_do_mux);

    ~mux4bit_4to1_do_mux();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<1> > sel_tmp_fu_117_p2;
    sc_signal< sc_lv<1> > tmp_10_fu_113_p1;
    sc_signal< sc_lv<1> > sel_tmp6_fu_141_p2;
    sc_signal< sc_lv<1> > tmp_11_fu_147_p1;
    sc_signal< sc_lv<1> > tmp_12_fu_151_p1;
    sc_signal< sc_lv<1> > sel_tmp4_fu_135_p2;
    sc_signal< sc_lv<1> > sel_tmp2_fu_129_p2;
    sc_signal< sc_lv<1> > tmp_9_fu_109_p1;
    sc_signal< sc_lv<1> > sel_tmp1_fu_123_p2;
    sc_signal< sc_lv<1> > or_cond_fu_163_p2;
    sc_signal< sc_lv<1> > tmp_13_fu_155_p3;
    sc_signal< sc_lv<1> > newSel1_fu_169_p3;
    sc_signal< sc_lv<1> > sel_tmp8_fu_217_p2;
    sc_signal< sc_lv<1> > tmp_17_fu_209_p3;
    sc_signal< sc_lv<1> > sel_tmp7_fu_241_p2;
    sc_signal< sc_lv<1> > tmp_14_fu_185_p3;
    sc_signal< sc_lv<1> > tmp_15_fu_193_p3;
    sc_signal< sc_lv<1> > sel_tmp5_fu_235_p2;
    sc_signal< sc_lv<1> > sel_tmp3_fu_229_p2;
    sc_signal< sc_lv<1> > tmp_16_fu_201_p3;
    sc_signal< sc_lv<1> > sel_tmp9_fu_223_p2;
    sc_signal< sc_lv<1> > or_cond1_fu_255_p2;
    sc_signal< sc_lv<1> > newSel3_fu_247_p3;
    sc_signal< sc_lv<1> > newSel4_fu_261_p3;
    sc_signal< sc_lv<1> > sel_tmp10_fu_309_p2;
    sc_signal< sc_lv<1> > tmp_21_fu_301_p3;
    sc_signal< sc_lv<1> > sel_tmp14_fu_333_p2;
    sc_signal< sc_lv<1> > tmp_18_fu_277_p3;
    sc_signal< sc_lv<1> > tmp_19_fu_285_p3;
    sc_signal< sc_lv<1> > sel_tmp13_fu_327_p2;
    sc_signal< sc_lv<1> > sel_tmp12_fu_321_p2;
    sc_signal< sc_lv<1> > tmp_20_fu_293_p3;
    sc_signal< sc_lv<1> > sel_tmp11_fu_315_p2;
    sc_signal< sc_lv<1> > or_cond2_fu_347_p2;
    sc_signal< sc_lv<1> > newSel6_fu_339_p3;
    sc_signal< sc_lv<1> > newSel7_fu_353_p3;
    sc_signal< sc_lv<1> > sel_tmp15_fu_401_p2;
    sc_signal< sc_lv<1> > tmp_25_fu_393_p3;
    sc_signal< sc_lv<1> > sel_tmp19_fu_425_p2;
    sc_signal< sc_lv<1> > tmp_22_fu_369_p3;
    sc_signal< sc_lv<1> > tmp_23_fu_377_p3;
    sc_signal< sc_lv<1> > sel_tmp18_fu_419_p2;
    sc_signal< sc_lv<1> > sel_tmp17_fu_413_p2;
    sc_signal< sc_lv<1> > tmp_24_fu_385_p3;
    sc_signal< sc_lv<1> > sel_tmp16_fu_407_p2;
    sc_signal< sc_lv<1> > or_cond3_fu_439_p2;
    sc_signal< sc_lv<1> > newSel9_fu_431_p3;
    sc_signal< sc_lv<1> > newSel_fu_445_p3;
    sc_signal< sc_lv<1> > newSel10_fu_453_p3;
    sc_signal< sc_lv<1> > newSel8_fu_361_p3;
    sc_signal< sc_lv<1> > newSel5_fu_269_p3;
    sc_signal< sc_lv<1> > newSel2_fu_177_p3;
    static const bool ap_true;
    static const sc_logic ap_const_logic_0;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<1> ap_const_lv1_0;
    // Thread declarations
    void thread_newSel10_fu_453_p3();
    void thread_newSel1_fu_169_p3();
    void thread_newSel2_fu_177_p3();
    void thread_newSel3_fu_247_p3();
    void thread_newSel4_fu_261_p3();
    void thread_newSel5_fu_269_p3();
    void thread_newSel6_fu_339_p3();
    void thread_newSel7_fu_353_p3();
    void thread_newSel8_fu_361_p3();
    void thread_newSel9_fu_431_p3();
    void thread_newSel_fu_445_p3();
    void thread_or_cond1_fu_255_p2();
    void thread_or_cond2_fu_347_p2();
    void thread_or_cond3_fu_439_p2();
    void thread_or_cond_fu_163_p2();
    void thread_out_r();
    void thread_out_r_ap_vld();
    void thread_sel_tmp10_fu_309_p2();
    void thread_sel_tmp11_fu_315_p2();
    void thread_sel_tmp12_fu_321_p2();
    void thread_sel_tmp13_fu_327_p2();
    void thread_sel_tmp14_fu_333_p2();
    void thread_sel_tmp15_fu_401_p2();
    void thread_sel_tmp16_fu_407_p2();
    void thread_sel_tmp17_fu_413_p2();
    void thread_sel_tmp18_fu_419_p2();
    void thread_sel_tmp19_fu_425_p2();
    void thread_sel_tmp1_fu_123_p2();
    void thread_sel_tmp2_fu_129_p2();
    void thread_sel_tmp3_fu_229_p2();
    void thread_sel_tmp4_fu_135_p2();
    void thread_sel_tmp5_fu_235_p2();
    void thread_sel_tmp6_fu_141_p2();
    void thread_sel_tmp7_fu_241_p2();
    void thread_sel_tmp8_fu_217_p2();
    void thread_sel_tmp9_fu_223_p2();
    void thread_sel_tmp_fu_117_p2();
    void thread_tmp_10_fu_113_p1();
    void thread_tmp_11_fu_147_p1();
    void thread_tmp_12_fu_151_p1();
    void thread_tmp_13_fu_155_p3();
    void thread_tmp_14_fu_185_p3();
    void thread_tmp_15_fu_193_p3();
    void thread_tmp_16_fu_201_p3();
    void thread_tmp_17_fu_209_p3();
    void thread_tmp_18_fu_277_p3();
    void thread_tmp_19_fu_285_p3();
    void thread_tmp_20_fu_293_p3();
    void thread_tmp_21_fu_301_p3();
    void thread_tmp_22_fu_369_p3();
    void thread_tmp_23_fu_377_p3();
    void thread_tmp_24_fu_385_p3();
    void thread_tmp_25_fu_393_p3();
    void thread_tmp_9_fu_109_p1();
};

}

using namespace ap_rtl;

#endif
