-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2015.4
-- Copyright (C) 2015 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity FullSubtractor is
port (
    A : IN STD_LOGIC;
    B : IN STD_LOGIC;
    Bin : IN STD_LOGIC;
    D : OUT STD_LOGIC;
    Bout : OUT STD_LOGIC );
end;


architecture behav of FullSubtractor is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "FullSubtractor,hls_ip_2015_4,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.480000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=8}";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal stg_10_FullSubtractor_process_sub_fu_44_A : STD_LOGIC;
    signal stg_10_FullSubtractor_process_sub_fu_44_B : STD_LOGIC;
    signal stg_10_FullSubtractor_process_sub_fu_44_Bin : STD_LOGIC;
    signal stg_10_FullSubtractor_process_sub_fu_44_D : STD_LOGIC;
    signal stg_10_FullSubtractor_process_sub_fu_44_D_ap_vld : STD_LOGIC;
    signal stg_10_FullSubtractor_process_sub_fu_44_Bout : STD_LOGIC;
    signal stg_10_FullSubtractor_process_sub_fu_44_Bout_ap_vld : STD_LOGIC;
    signal FullSubtractor_ssdm_thread_s_load_fu_58_p1 : STD_LOGIC_VECTOR (0 downto 0);

    component FullSubtractor_process_sub IS
    port (
        A : IN STD_LOGIC;
        B : IN STD_LOGIC;
        Bin : IN STD_LOGIC;
        D : OUT STD_LOGIC;
        D_ap_vld : OUT STD_LOGIC;
        Bout : OUT STD_LOGIC;
        Bout_ap_vld : OUT STD_LOGIC );
    end component;



begin
    stg_10_FullSubtractor_process_sub_fu_44 : component FullSubtractor_process_sub
    port map (
        A => stg_10_FullSubtractor_process_sub_fu_44_A,
        B => stg_10_FullSubtractor_process_sub_fu_44_B,
        Bin => stg_10_FullSubtractor_process_sub_fu_44_Bin,
        D => stg_10_FullSubtractor_process_sub_fu_44_D,
        D_ap_vld => stg_10_FullSubtractor_process_sub_fu_44_D_ap_vld,
        Bout => stg_10_FullSubtractor_process_sub_fu_44_Bout,
        Bout_ap_vld => stg_10_FullSubtractor_process_sub_fu_44_Bout_ap_vld);




    Bout <= stg_10_FullSubtractor_process_sub_fu_44_Bout;
    D <= stg_10_FullSubtractor_process_sub_fu_44_D;
    FullSubtractor_ssdm_thread_s_load_fu_58_p1 <= ap_const_lv1_0;
    stg_10_FullSubtractor_process_sub_fu_44_A <= A;
    stg_10_FullSubtractor_process_sub_fu_44_B <= B;
    stg_10_FullSubtractor_process_sub_fu_44_Bin <= Bin;
end behav;
