-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2015.4
-- Copyright (C) 2015 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity FullSubtractor_process_sub is
port (
    A : IN STD_LOGIC;
    B : IN STD_LOGIC;
    Bin : IN STD_LOGIC;
    D : OUT STD_LOGIC;
    D_ap_vld : OUT STD_LOGIC;
    Bout : OUT STD_LOGIC;
    Bout_ap_vld : OUT STD_LOGIC );
end;


architecture behav of FullSubtractor_process_sub is 
    constant ap_true : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

    signal tmp1_fu_82_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_82_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_82_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal v_fu_88_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_95_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_101_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_95_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_107_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_113_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_107_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_101_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_113_p2 : STD_LOGIC_VECTOR (0 downto 0);


begin



    Bout <= (tmp_3_fu_101_p2(0) or tmp_5_fu_113_p2(0));
    Bout_ap_vld <= ap_const_logic_1;
    D <= (tmp1_fu_82_p2(0) xor v_fu_88_p1(0));
    D_ap_vld <= ap_const_logic_1;
    tmp1_fu_82_p0 <= (0=>B, others=>'-');
    tmp1_fu_82_p1 <= (0=>Bin, others=>'-');
    tmp1_fu_82_p2 <= (tmp1_fu_82_p0 xor tmp1_fu_82_p1);
    tmp_2_fu_95_p0 <= (0=>A, others=>'-');
    tmp_2_fu_95_p2 <= (tmp_2_fu_95_p0 xor ap_const_lv1_1);
    tmp_3_fu_101_p0 <= (0=>B, others=>'-');
    tmp_3_fu_101_p2 <= (tmp_3_fu_101_p0 and tmp_2_fu_95_p2);
    tmp_4_fu_107_p0 <= (0=>B, others=>'-');
    tmp_4_fu_107_p2 <= (tmp_4_fu_107_p0 or tmp_2_fu_95_p2);
    tmp_5_fu_113_p0 <= (0=>Bin, others=>'-');
    tmp_5_fu_113_p2 <= (tmp_5_fu_113_p0 and tmp_4_fu_107_p2);
    v_fu_88_p1 <= (0=>A, others=>'-');
end behav;
