// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="decoder_2to4,hls_ip_2015_4,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.877000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=4}" *)

module decoder_2to4 (
        din,
        dout
);

parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;

input  [1:0] din;
output  [3:0] dout;

wire   [1:0] stg_7_decoder_2to4_do_decode_fu_34_din;
wire   [3:0] stg_7_decoder_2to4_do_decode_fu_34_dout;
wire    stg_7_decoder_2to4_do_decode_fu_34_dout_ap_vld;
wire   [0:0] decoder_2to4_ssdm_thread_M_s_load_fu_42_p1;


decoder_2to4_do_decode stg_7_decoder_2to4_do_decode_fu_34(
    .din( stg_7_decoder_2to4_do_decode_fu_34_din ),
    .dout( stg_7_decoder_2to4_do_decode_fu_34_dout ),
    .dout_ap_vld( stg_7_decoder_2to4_do_decode_fu_34_dout_ap_vld )
);



assign decoder_2to4_ssdm_thread_M_s_load_fu_42_p1 = ap_const_lv1_0;

assign dout = stg_7_decoder_2to4_do_decode_fu_34_dout;

assign stg_7_decoder_2to4_do_decode_fu_34_din = din;


endmodule //decoder_2to4

