// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module decoder_2to4_do_decode (
        din,
        dout,
        dout_ap_vld
);

parameter    ap_true = 1'b1;
parameter    ap_const_lv4_8 = 4'b1000;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv4_4 = 4'b100;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv4_2 = 4'b10;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_const_logic_1 = 1'b1;

input  [1:0] din;
output  [3:0] dout;
output   dout_ap_vld;

reg[3:0] dout;
reg dout_ap_vld;
wire   [1:0] val_V_read_fu_56_p2;




always @ (val_V_read_fu_56_p2) begin
    if ((~(val_V_read_fu_56_p2 == ap_const_lv2_3) & ~(val_V_read_fu_56_p2 == ap_const_lv2_2) & ~(val_V_read_fu_56_p2 == ap_const_lv2_1) & ~(val_V_read_fu_56_p2 == ap_const_lv2_0))) begin
        dout = ap_const_lv4_0;
    end else if ((val_V_read_fu_56_p2 == ap_const_lv2_0)) begin
        dout = ap_const_lv4_1;
    end else if ((val_V_read_fu_56_p2 == ap_const_lv2_1)) begin
        dout = ap_const_lv4_2;
    end else if ((val_V_read_fu_56_p2 == ap_const_lv2_2)) begin
        dout = ap_const_lv4_4;
    end else if ((val_V_read_fu_56_p2 == ap_const_lv2_3)) begin
        dout = ap_const_lv4_8;
    end else begin
        dout = 'bx;
    end
end

always @ (val_V_read_fu_56_p2) begin
    if (((val_V_read_fu_56_p2 == ap_const_lv2_3) | (val_V_read_fu_56_p2 == ap_const_lv2_2) | (val_V_read_fu_56_p2 == ap_const_lv2_1) | (val_V_read_fu_56_p2 == ap_const_lv2_0) | (~(val_V_read_fu_56_p2 == ap_const_lv2_3) & ~(val_V_read_fu_56_p2 == ap_const_lv2_2) & ~(val_V_read_fu_56_p2 == ap_const_lv2_1) & ~(val_V_read_fu_56_p2 == ap_const_lv2_0)))) begin
        dout_ap_vld = ap_const_logic_1;
    end else begin
        dout_ap_vld = ap_const_logic_0;
    end
end

assign val_V_read_fu_56_p2 = din;


endmodule //decoder_2to4_do_decode

