// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _FullSubtractor_process_sub_HH_
#define _FullSubtractor_process_sub_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct FullSubtractor_process_sub : public sc_module {
    // Port declarations 7
    sc_in< sc_logic > A;
    sc_in< sc_logic > B;
    sc_in< sc_logic > Bin;
    sc_out< sc_logic > D;
    sc_out< sc_logic > D_ap_vld;
    sc_out< sc_logic > Bout;
    sc_out< sc_logic > Bout_ap_vld;


    // Module declarations
    FullSubtractor_process_sub(sc_module_name name);
    SC_HAS_PROCESS(FullSubtractor_process_sub);

    ~FullSubtractor_process_sub();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<1> > tmp1_fu_82_p0;
    sc_signal< sc_lv<1> > tmp1_fu_82_p1;
    sc_signal< sc_lv<1> > tmp1_fu_82_p2;
    sc_signal< sc_lv<1> > v_fu_88_p1;
    sc_signal< sc_lv<1> > tmp_2_fu_95_p0;
    sc_signal< sc_lv<1> > tmp_3_fu_101_p0;
    sc_signal< sc_lv<1> > tmp_2_fu_95_p2;
    sc_signal< sc_lv<1> > tmp_4_fu_107_p0;
    sc_signal< sc_lv<1> > tmp_5_fu_113_p0;
    sc_signal< sc_lv<1> > tmp_4_fu_107_p2;
    sc_signal< sc_lv<1> > tmp_3_fu_101_p2;
    sc_signal< sc_lv<1> > tmp_5_fu_113_p2;
    static const bool ap_true;
    static const sc_logic ap_const_logic_0;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<1> ap_const_lv1_1;
    // Thread declarations
    void thread_Bout();
    void thread_Bout_ap_vld();
    void thread_D();
    void thread_D_ap_vld();
    void thread_tmp1_fu_82_p0();
    void thread_tmp1_fu_82_p1();
    void thread_tmp1_fu_82_p2();
    void thread_tmp_2_fu_95_p0();
    void thread_tmp_2_fu_95_p2();
    void thread_tmp_3_fu_101_p0();
    void thread_tmp_3_fu_101_p2();
    void thread_tmp_4_fu_107_p0();
    void thread_tmp_4_fu_107_p2();
    void thread_tmp_5_fu_113_p0();
    void thread_tmp_5_fu_113_p2();
    void thread_v_fu_88_p1();
};

}

using namespace ap_rtl;

#endif
