// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _FullSubtractor_HH_
#define _FullSubtractor_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "FullSubtractor_process_sub.h"

namespace ap_rtl {

struct FullSubtractor : public sc_module {
    // Port declarations 5
    sc_in< sc_logic > A;
    sc_in< sc_logic > B;
    sc_in< sc_logic > Bin;
    sc_out< sc_logic > D;
    sc_out< sc_logic > Bout;
    // Internal clock declarations for combination SystemC design. 
    sc_clock ap_sc_inter_clock;


    // Module declarations
    FullSubtractor(sc_module_name name);
    SC_HAS_PROCESS(FullSubtractor);

    ~FullSubtractor();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    FullSubtractor_process_sub* stg_10_FullSubtractor_process_sub_fu_44;
    sc_signal< sc_logic > stg_10_FullSubtractor_process_sub_fu_44_A;
    sc_signal< sc_logic > stg_10_FullSubtractor_process_sub_fu_44_B;
    sc_signal< sc_logic > stg_10_FullSubtractor_process_sub_fu_44_Bin;
    sc_signal< sc_logic > stg_10_FullSubtractor_process_sub_fu_44_D;
    sc_signal< sc_logic > stg_10_FullSubtractor_process_sub_fu_44_D_ap_vld;
    sc_signal< sc_logic > stg_10_FullSubtractor_process_sub_fu_44_Bout;
    sc_signal< sc_logic > stg_10_FullSubtractor_process_sub_fu_44_Bout_ap_vld;
    sc_signal< sc_lv<1> > FullSubtractor_ssdm_thread_s_load_fu_58_p1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_Bout();
    void thread_D();
    void thread_FullSubtractor_ssdm_thread_s_load_fu_58_p1();
    void thread_stg_10_FullSubtractor_process_sub_fu_44_A();
    void thread_stg_10_FullSubtractor_process_sub_fu_44_B();
    void thread_stg_10_FullSubtractor_process_sub_fu_44_Bin();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
