-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2015.4
-- Copyright (C) 2015 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mux4bit_4to1_do_mux is
port (
    in0 : IN STD_LOGIC_VECTOR (3 downto 0);
    in1 : IN STD_LOGIC_VECTOR (3 downto 0);
    in2 : IN STD_LOGIC_VECTOR (3 downto 0);
    in3 : IN STD_LOGIC_VECTOR (3 downto 0);
    sel : IN STD_LOGIC_VECTOR (1 downto 0);
    out_r : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_r_ap_vld : OUT STD_LOGIC );
end;


architecture behav of mux4bit_4to1_do_mux is 
    constant ap_true : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";

    signal sel_tmp_fu_117_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_113_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_fu_141_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_147_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_151_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp4_fu_135_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_129_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_109_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_fu_123_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_fu_163_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_155_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel1_fu_169_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp8_fu_217_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_fu_209_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_fu_241_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_185_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_fu_193_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp5_fu_235_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp3_fu_229_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_201_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp9_fu_223_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond1_fu_255_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel3_fu_247_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel4_fu_261_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp10_fu_309_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_fu_301_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp14_fu_333_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_fu_277_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_fu_285_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp13_fu_327_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp12_fu_321_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_fu_293_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp11_fu_315_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond2_fu_347_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel6_fu_339_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel7_fu_353_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp15_fu_401_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_fu_393_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp19_fu_425_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_fu_369_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_fu_377_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp18_fu_419_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp17_fu_413_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_fu_385_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp16_fu_407_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond3_fu_439_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel9_fu_431_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel_fu_445_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel10_fu_453_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel8_fu_361_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel5_fu_269_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel2_fu_177_p3 : STD_LOGIC_VECTOR (0 downto 0);


begin



    newSel10_fu_453_p3 <= 
        newSel9_fu_431_p3 when (or_cond3_fu_439_p2(0) = '1') else 
        newSel_fu_445_p3;
    newSel1_fu_169_p3 <= 
        tmp_9_fu_109_p1 when (sel_tmp2_fu_129_p2(0) = '1') else 
        sel_tmp1_fu_123_p2;
    newSel2_fu_177_p3 <= 
        tmp_13_fu_155_p3 when (or_cond_fu_163_p2(0) = '1') else 
        newSel1_fu_169_p3;
    newSel3_fu_247_p3 <= 
        tmp_14_fu_185_p3 when (sel_tmp7_fu_241_p2(0) = '1') else 
        tmp_15_fu_193_p3;
    newSel4_fu_261_p3 <= 
        tmp_16_fu_201_p3 when (sel_tmp3_fu_229_p2(0) = '1') else 
        sel_tmp9_fu_223_p2;
    newSel5_fu_269_p3 <= 
        newSel3_fu_247_p3 when (or_cond1_fu_255_p2(0) = '1') else 
        newSel4_fu_261_p3;
    newSel6_fu_339_p3 <= 
        tmp_18_fu_277_p3 when (sel_tmp14_fu_333_p2(0) = '1') else 
        tmp_19_fu_285_p3;
    newSel7_fu_353_p3 <= 
        tmp_20_fu_293_p3 when (sel_tmp12_fu_321_p2(0) = '1') else 
        sel_tmp11_fu_315_p2;
    newSel8_fu_361_p3 <= 
        newSel6_fu_339_p3 when (or_cond2_fu_347_p2(0) = '1') else 
        newSel7_fu_353_p3;
    newSel9_fu_431_p3 <= 
        tmp_22_fu_369_p3 when (sel_tmp19_fu_425_p2(0) = '1') else 
        tmp_23_fu_377_p3;
    newSel_fu_445_p3 <= 
        tmp_24_fu_385_p3 when (sel_tmp17_fu_413_p2(0) = '1') else 
        sel_tmp16_fu_407_p2;
    or_cond1_fu_255_p2 <= (sel_tmp7_fu_241_p2 or sel_tmp5_fu_235_p2);
    or_cond2_fu_347_p2 <= (sel_tmp14_fu_333_p2 or sel_tmp13_fu_327_p2);
    or_cond3_fu_439_p2 <= (sel_tmp19_fu_425_p2 or sel_tmp18_fu_419_p2);
    or_cond_fu_163_p2 <= (sel_tmp6_fu_141_p2 or sel_tmp4_fu_135_p2);
    out_r <= (((newSel10_fu_453_p3 & newSel8_fu_361_p3) & newSel5_fu_269_p3) & newSel2_fu_177_p3);
    out_r_ap_vld <= ap_const_logic_1;
    sel_tmp10_fu_309_p2 <= "1" when (sel = ap_const_lv2_3) else "0";
    sel_tmp11_fu_315_p2 <= (sel_tmp10_fu_309_p2 and tmp_21_fu_301_p3);
    sel_tmp12_fu_321_p2 <= "1" when (sel = ap_const_lv2_2) else "0";
    sel_tmp13_fu_327_p2 <= "1" when (sel = ap_const_lv2_1) else "0";
    sel_tmp14_fu_333_p2 <= "1" when (sel = ap_const_lv2_0) else "0";
    sel_tmp15_fu_401_p2 <= "1" when (sel = ap_const_lv2_3) else "0";
    sel_tmp16_fu_407_p2 <= (sel_tmp15_fu_401_p2 and tmp_25_fu_393_p3);
    sel_tmp17_fu_413_p2 <= "1" when (sel = ap_const_lv2_2) else "0";
    sel_tmp18_fu_419_p2 <= "1" when (sel = ap_const_lv2_1) else "0";
    sel_tmp19_fu_425_p2 <= "1" when (sel = ap_const_lv2_0) else "0";
    sel_tmp1_fu_123_p2 <= (sel_tmp_fu_117_p2 and tmp_10_fu_113_p1);
    sel_tmp2_fu_129_p2 <= "1" when (sel = ap_const_lv2_2) else "0";
    sel_tmp3_fu_229_p2 <= "1" when (sel = ap_const_lv2_2) else "0";
    sel_tmp4_fu_135_p2 <= "1" when (sel = ap_const_lv2_1) else "0";
    sel_tmp5_fu_235_p2 <= "1" when (sel = ap_const_lv2_1) else "0";
    sel_tmp6_fu_141_p2 <= "1" when (sel = ap_const_lv2_0) else "0";
    sel_tmp7_fu_241_p2 <= "1" when (sel = ap_const_lv2_0) else "0";
    sel_tmp8_fu_217_p2 <= "1" when (sel = ap_const_lv2_3) else "0";
    sel_tmp9_fu_223_p2 <= (sel_tmp8_fu_217_p2 and tmp_17_fu_209_p3);
    sel_tmp_fu_117_p2 <= "1" when (sel = ap_const_lv2_3) else "0";
    tmp_10_fu_113_p1 <= in3(1 - 1 downto 0);
    tmp_11_fu_147_p1 <= in0(1 - 1 downto 0);
    tmp_12_fu_151_p1 <= in1(1 - 1 downto 0);
    tmp_13_fu_155_p3 <= 
        tmp_11_fu_147_p1 when (sel_tmp6_fu_141_p2(0) = '1') else 
        tmp_12_fu_151_p1;
    tmp_14_fu_185_p3 <= in0(1 downto 1);
    tmp_15_fu_193_p3 <= in1(1 downto 1);
    tmp_16_fu_201_p3 <= in2(1 downto 1);
    tmp_17_fu_209_p3 <= in3(1 downto 1);
    tmp_18_fu_277_p3 <= in0(2 downto 2);
    tmp_19_fu_285_p3 <= in1(2 downto 2);
    tmp_20_fu_293_p3 <= in2(2 downto 2);
    tmp_21_fu_301_p3 <= in3(2 downto 2);
    tmp_22_fu_369_p3 <= in0(3 downto 3);
    tmp_23_fu_377_p3 <= in1(3 downto 3);
    tmp_24_fu_385_p3 <= in2(3 downto 3);
    tmp_25_fu_393_p3 <= in3(3 downto 3);
    tmp_9_fu_109_p1 <= in2(1 - 1 downto 0);
end behav;
