-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2015.4
-- Copyright (C) 2015 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity decoder_2to4 is
port (
    din : IN STD_LOGIC_VECTOR (1 downto 0);
    dout : OUT STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of decoder_2to4 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "decoder_2to4,hls_ip_2015_4,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.877000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=4}";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal stg_7_decoder_2to4_do_decode_fu_34_din : STD_LOGIC_VECTOR (1 downto 0);
    signal stg_7_decoder_2to4_do_decode_fu_34_dout : STD_LOGIC_VECTOR (3 downto 0);
    signal stg_7_decoder_2to4_do_decode_fu_34_dout_ap_vld : STD_LOGIC;
    signal decoder_2to4_ssdm_thread_M_s_load_fu_42_p1 : STD_LOGIC_VECTOR (0 downto 0);

    component decoder_2to4_do_decode IS
    port (
        din : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (3 downto 0);
        dout_ap_vld : OUT STD_LOGIC );
    end component;



begin
    stg_7_decoder_2to4_do_decode_fu_34 : component decoder_2to4_do_decode
    port map (
        din => stg_7_decoder_2to4_do_decode_fu_34_din,
        dout => stg_7_decoder_2to4_do_decode_fu_34_dout,
        dout_ap_vld => stg_7_decoder_2to4_do_decode_fu_34_dout_ap_vld);




    decoder_2to4_ssdm_thread_M_s_load_fu_42_p1 <= ap_const_lv1_0;
    dout <= stg_7_decoder_2to4_do_decode_fu_34_dout;
    stg_7_decoder_2to4_do_decode_fu_34_din <= din;
end behav;
