-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2015.4
-- Copyright (C) 2015 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ALU is
port (
    A : IN STD_LOGIC_VECTOR (3 downto 0);
    B : IN STD_LOGIC_VECTOR (3 downto 0);
    op_code : IN STD_LOGIC_VECTOR (2 downto 0);
    result : OUT STD_LOGIC_VECTOR (3 downto 0);
    carry_borrow : OUT STD_LOGIC );
end;


architecture behav of ALU is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "ALU,hls_ip_2015_4,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.975000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=64}";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal stg_10_ALU_perform_operation_fu_48_A : STD_LOGIC_VECTOR (3 downto 0);
    signal stg_10_ALU_perform_operation_fu_48_B : STD_LOGIC_VECTOR (3 downto 0);
    signal stg_10_ALU_perform_operation_fu_48_op_code : STD_LOGIC_VECTOR (2 downto 0);
    signal stg_10_ALU_perform_operation_fu_48_result : STD_LOGIC_VECTOR (3 downto 0);
    signal stg_10_ALU_perform_operation_fu_48_result_ap_vld : STD_LOGIC;
    signal stg_10_ALU_perform_operation_fu_48_carry_borrow : STD_LOGIC;
    signal stg_10_ALU_perform_operation_fu_48_carry_borrow_ap_vld : STD_LOGIC;
    signal ALU_ssdm_thread_M_perform_o_load_fu_62_p1 : STD_LOGIC_VECTOR (0 downto 0);

    component ALU_perform_operation IS
    port (
        A : IN STD_LOGIC_VECTOR (3 downto 0);
        B : IN STD_LOGIC_VECTOR (3 downto 0);
        op_code : IN STD_LOGIC_VECTOR (2 downto 0);
        result : OUT STD_LOGIC_VECTOR (3 downto 0);
        result_ap_vld : OUT STD_LOGIC;
        carry_borrow : OUT STD_LOGIC;
        carry_borrow_ap_vld : OUT STD_LOGIC );
    end component;



begin
    stg_10_ALU_perform_operation_fu_48 : component ALU_perform_operation
    port map (
        A => stg_10_ALU_perform_operation_fu_48_A,
        B => stg_10_ALU_perform_operation_fu_48_B,
        op_code => stg_10_ALU_perform_operation_fu_48_op_code,
        result => stg_10_ALU_perform_operation_fu_48_result,
        result_ap_vld => stg_10_ALU_perform_operation_fu_48_result_ap_vld,
        carry_borrow => stg_10_ALU_perform_operation_fu_48_carry_borrow,
        carry_borrow_ap_vld => stg_10_ALU_perform_operation_fu_48_carry_borrow_ap_vld);




    ALU_ssdm_thread_M_perform_o_load_fu_62_p1 <= ap_const_lv1_0;
    carry_borrow <= stg_10_ALU_perform_operation_fu_48_carry_borrow;
    result <= stg_10_ALU_perform_operation_fu_48_result;
    stg_10_ALU_perform_operation_fu_48_A <= A;
    stg_10_ALU_perform_operation_fu_48_B <= B;
    stg_10_ALU_perform_operation_fu_48_op_code <= op_code;
end behav;
