// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="FullSubtractor,hls_ip_2015_4,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.480000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=8}" *)

module FullSubtractor (
        A,
        B,
        Bin,
        D,
        Bout
);

parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;

input   A;
input   B;
input   Bin;
output   D;
output   Bout;

wire    stg_10_FullSubtractor_process_sub_fu_44_A;
wire    stg_10_FullSubtractor_process_sub_fu_44_B;
wire    stg_10_FullSubtractor_process_sub_fu_44_Bin;
wire    stg_10_FullSubtractor_process_sub_fu_44_D;
wire    stg_10_FullSubtractor_process_sub_fu_44_D_ap_vld;
wire    stg_10_FullSubtractor_process_sub_fu_44_Bout;
wire    stg_10_FullSubtractor_process_sub_fu_44_Bout_ap_vld;
wire   [0:0] FullSubtractor_ssdm_thread_s_load_fu_58_p1;


FullSubtractor_process_sub stg_10_FullSubtractor_process_sub_fu_44(
    .A( stg_10_FullSubtractor_process_sub_fu_44_A ),
    .B( stg_10_FullSubtractor_process_sub_fu_44_B ),
    .Bin( stg_10_FullSubtractor_process_sub_fu_44_Bin ),
    .D( stg_10_FullSubtractor_process_sub_fu_44_D ),
    .D_ap_vld( stg_10_FullSubtractor_process_sub_fu_44_D_ap_vld ),
    .Bout( stg_10_FullSubtractor_process_sub_fu_44_Bout ),
    .Bout_ap_vld( stg_10_FullSubtractor_process_sub_fu_44_Bout_ap_vld )
);



assign Bout = stg_10_FullSubtractor_process_sub_fu_44_Bout;

assign D = stg_10_FullSubtractor_process_sub_fu_44_D;

assign FullSubtractor_ssdm_thread_s_load_fu_58_p1 = ap_const_lv1_0;

assign stg_10_FullSubtractor_process_sub_fu_44_A = A;

assign stg_10_FullSubtractor_process_sub_fu_44_B = B;

assign stg_10_FullSubtractor_process_sub_fu_44_Bin = Bin;


endmodule //FullSubtractor

