// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module mux4bit_4to1_do_mux (
        in0,
        in1,
        in2,
        in3,
        sel,
        out_r,
        out_r_ap_vld
);

parameter    ap_true = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv1_0 = 1'b0;

input  [3:0] in0;
input  [3:0] in1;
input  [3:0] in2;
input  [3:0] in3;
input  [1:0] sel;
output  [3:0] out_r;
output   out_r_ap_vld;

wire   [0:0] sel_tmp_fu_117_p2;
wire   [0:0] tmp_10_fu_113_p1;
wire   [0:0] sel_tmp6_fu_141_p2;
wire   [0:0] tmp_11_fu_147_p1;
wire   [0:0] tmp_12_fu_151_p1;
wire   [0:0] sel_tmp4_fu_135_p2;
wire   [0:0] sel_tmp2_fu_129_p2;
wire   [0:0] tmp_9_fu_109_p1;
wire   [0:0] sel_tmp1_fu_123_p2;
wire   [0:0] or_cond_fu_163_p2;
wire   [0:0] tmp_13_fu_155_p3;
wire   [0:0] newSel1_fu_169_p3;
wire   [0:0] sel_tmp8_fu_217_p2;
wire   [0:0] tmp_17_fu_209_p3;
wire   [0:0] sel_tmp7_fu_241_p2;
wire   [0:0] tmp_14_fu_185_p3;
wire   [0:0] tmp_15_fu_193_p3;
wire   [0:0] sel_tmp5_fu_235_p2;
wire   [0:0] sel_tmp3_fu_229_p2;
wire   [0:0] tmp_16_fu_201_p3;
wire   [0:0] sel_tmp9_fu_223_p2;
wire   [0:0] or_cond1_fu_255_p2;
wire   [0:0] newSel3_fu_247_p3;
wire   [0:0] newSel4_fu_261_p3;
wire   [0:0] sel_tmp10_fu_309_p2;
wire   [0:0] tmp_21_fu_301_p3;
wire   [0:0] sel_tmp14_fu_333_p2;
wire   [0:0] tmp_18_fu_277_p3;
wire   [0:0] tmp_19_fu_285_p3;
wire   [0:0] sel_tmp13_fu_327_p2;
wire   [0:0] sel_tmp12_fu_321_p2;
wire   [0:0] tmp_20_fu_293_p3;
wire   [0:0] sel_tmp11_fu_315_p2;
wire   [0:0] or_cond2_fu_347_p2;
wire   [0:0] newSel6_fu_339_p3;
wire   [0:0] newSel7_fu_353_p3;
wire   [0:0] sel_tmp15_fu_401_p2;
wire   [0:0] tmp_25_fu_393_p3;
wire   [0:0] sel_tmp19_fu_425_p2;
wire   [0:0] tmp_22_fu_369_p3;
wire   [0:0] tmp_23_fu_377_p3;
wire   [0:0] sel_tmp18_fu_419_p2;
wire   [0:0] sel_tmp17_fu_413_p2;
wire   [0:0] tmp_24_fu_385_p3;
wire   [0:0] sel_tmp16_fu_407_p2;
wire   [0:0] or_cond3_fu_439_p2;
wire   [0:0] newSel9_fu_431_p3;
wire   [0:0] newSel_fu_445_p3;
wire   [0:0] newSel10_fu_453_p3;
wire   [0:0] newSel8_fu_361_p3;
wire   [0:0] newSel5_fu_269_p3;
wire   [0:0] newSel2_fu_177_p3;




assign out_r_ap_vld = ap_const_logic_1;

assign newSel10_fu_453_p3 = ((or_cond3_fu_439_p2[0:0] === 1'b1) ? newSel9_fu_431_p3 : newSel_fu_445_p3);

assign newSel1_fu_169_p3 = ((sel_tmp2_fu_129_p2[0:0] === 1'b1) ? tmp_9_fu_109_p1 : sel_tmp1_fu_123_p2);

assign newSel2_fu_177_p3 = ((or_cond_fu_163_p2[0:0] === 1'b1) ? tmp_13_fu_155_p3 : newSel1_fu_169_p3);

assign newSel3_fu_247_p3 = ((sel_tmp7_fu_241_p2[0:0] === 1'b1) ? tmp_14_fu_185_p3 : tmp_15_fu_193_p3);

assign newSel4_fu_261_p3 = ((sel_tmp3_fu_229_p2[0:0] === 1'b1) ? tmp_16_fu_201_p3 : sel_tmp9_fu_223_p2);

assign newSel5_fu_269_p3 = ((or_cond1_fu_255_p2[0:0] === 1'b1) ? newSel3_fu_247_p3 : newSel4_fu_261_p3);

assign newSel6_fu_339_p3 = ((sel_tmp14_fu_333_p2[0:0] === 1'b1) ? tmp_18_fu_277_p3 : tmp_19_fu_285_p3);

assign newSel7_fu_353_p3 = ((sel_tmp12_fu_321_p2[0:0] === 1'b1) ? tmp_20_fu_293_p3 : sel_tmp11_fu_315_p2);

assign newSel8_fu_361_p3 = ((or_cond2_fu_347_p2[0:0] === 1'b1) ? newSel6_fu_339_p3 : newSel7_fu_353_p3);

assign newSel9_fu_431_p3 = ((sel_tmp19_fu_425_p2[0:0] === 1'b1) ? tmp_22_fu_369_p3 : tmp_23_fu_377_p3);

assign newSel_fu_445_p3 = ((sel_tmp17_fu_413_p2[0:0] === 1'b1) ? tmp_24_fu_385_p3 : sel_tmp16_fu_407_p2);

assign or_cond1_fu_255_p2 = (sel_tmp7_fu_241_p2 | sel_tmp5_fu_235_p2);

assign or_cond2_fu_347_p2 = (sel_tmp14_fu_333_p2 | sel_tmp13_fu_327_p2);

assign or_cond3_fu_439_p2 = (sel_tmp19_fu_425_p2 | sel_tmp18_fu_419_p2);

assign or_cond_fu_163_p2 = (sel_tmp6_fu_141_p2 | sel_tmp4_fu_135_p2);

assign out_r = {{{{newSel10_fu_453_p3}, {newSel8_fu_361_p3}}, {newSel5_fu_269_p3}}, {newSel2_fu_177_p3}};

assign sel_tmp10_fu_309_p2 = (sel == ap_const_lv2_3? 1'b1: 1'b0);

assign sel_tmp11_fu_315_p2 = (sel_tmp10_fu_309_p2 & tmp_21_fu_301_p3);

assign sel_tmp12_fu_321_p2 = (sel == ap_const_lv2_2? 1'b1: 1'b0);

assign sel_tmp13_fu_327_p2 = (sel == ap_const_lv2_1? 1'b1: 1'b0);

assign sel_tmp14_fu_333_p2 = (sel == ap_const_lv2_0? 1'b1: 1'b0);

assign sel_tmp15_fu_401_p2 = (sel == ap_const_lv2_3? 1'b1: 1'b0);

assign sel_tmp16_fu_407_p2 = (sel_tmp15_fu_401_p2 & tmp_25_fu_393_p3);

assign sel_tmp17_fu_413_p2 = (sel == ap_const_lv2_2? 1'b1: 1'b0);

assign sel_tmp18_fu_419_p2 = (sel == ap_const_lv2_1? 1'b1: 1'b0);

assign sel_tmp19_fu_425_p2 = (sel == ap_const_lv2_0? 1'b1: 1'b0);

assign sel_tmp1_fu_123_p2 = (sel_tmp_fu_117_p2 & tmp_10_fu_113_p1);

assign sel_tmp2_fu_129_p2 = (sel == ap_const_lv2_2? 1'b1: 1'b0);

assign sel_tmp3_fu_229_p2 = (sel == ap_const_lv2_2? 1'b1: 1'b0);

assign sel_tmp4_fu_135_p2 = (sel == ap_const_lv2_1? 1'b1: 1'b0);

assign sel_tmp5_fu_235_p2 = (sel == ap_const_lv2_1? 1'b1: 1'b0);

assign sel_tmp6_fu_141_p2 = (sel == ap_const_lv2_0? 1'b1: 1'b0);

assign sel_tmp7_fu_241_p2 = (sel == ap_const_lv2_0? 1'b1: 1'b0);

assign sel_tmp8_fu_217_p2 = (sel == ap_const_lv2_3? 1'b1: 1'b0);

assign sel_tmp9_fu_223_p2 = (sel_tmp8_fu_217_p2 & tmp_17_fu_209_p3);

assign sel_tmp_fu_117_p2 = (sel == ap_const_lv2_3? 1'b1: 1'b0);

assign tmp_10_fu_113_p1 = in3[0:0];

assign tmp_11_fu_147_p1 = in0[0:0];

assign tmp_12_fu_151_p1 = in1[0:0];

assign tmp_13_fu_155_p3 = ((sel_tmp6_fu_141_p2[0:0] === 1'b1) ? tmp_11_fu_147_p1 : tmp_12_fu_151_p1);

assign tmp_14_fu_185_p3 = in0[ap_const_lv32_1];

assign tmp_15_fu_193_p3 = in1[ap_const_lv32_1];

assign tmp_16_fu_201_p3 = in2[ap_const_lv32_1];

assign tmp_17_fu_209_p3 = in3[ap_const_lv32_1];

assign tmp_18_fu_277_p3 = in0[ap_const_lv32_2];

assign tmp_19_fu_285_p3 = in1[ap_const_lv32_2];

assign tmp_20_fu_293_p3 = in2[ap_const_lv32_2];

assign tmp_21_fu_301_p3 = in3[ap_const_lv32_2];

assign tmp_22_fu_369_p3 = in0[ap_const_lv32_3];

assign tmp_23_fu_377_p3 = in1[ap_const_lv32_3];

assign tmp_24_fu_385_p3 = in2[ap_const_lv32_3];

assign tmp_25_fu_393_p3 = in3[ap_const_lv32_3];

assign tmp_9_fu_109_p1 = in2[0:0];


endmodule //mux4bit_4to1_do_mux

