// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "decoder_2to4_do_decode.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const bool decoder_2to4_do_decode::ap_true = true;
const sc_lv<4> decoder_2to4_do_decode::ap_const_lv4_8 = "1000";
const sc_lv<2> decoder_2to4_do_decode::ap_const_lv2_3 = "11";
const sc_lv<4> decoder_2to4_do_decode::ap_const_lv4_4 = "100";
const sc_lv<2> decoder_2to4_do_decode::ap_const_lv2_2 = "10";
const sc_lv<4> decoder_2to4_do_decode::ap_const_lv4_2 = "10";
const sc_lv<2> decoder_2to4_do_decode::ap_const_lv2_1 = "1";
const sc_lv<4> decoder_2to4_do_decode::ap_const_lv4_1 = "1";
const sc_lv<2> decoder_2to4_do_decode::ap_const_lv2_0 = "00";
const sc_lv<4> decoder_2to4_do_decode::ap_const_lv4_0 = "0000";
const sc_logic decoder_2to4_do_decode::ap_const_logic_0 = sc_dt::Log_0;
const sc_logic decoder_2to4_do_decode::ap_const_logic_1 = sc_dt::Log_1;

decoder_2to4_do_decode::decoder_2to4_do_decode(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_dout);
    sensitive << ( val_V_read_fu_56_p2 );

    SC_METHOD(thread_dout_ap_vld);
    sensitive << ( val_V_read_fu_56_p2 );

    SC_METHOD(thread_val_V_read_fu_56_p2);
    sensitive << ( din );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "decoder_2to4_do_decode_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, din, "(port)din");
    sc_trace(mVcdFile, dout, "(port)dout");
    sc_trace(mVcdFile, dout_ap_vld, "(port)dout_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, val_V_read_fu_56_p2, "val_V_read_fu_56_p2");
#endif

    }
}

decoder_2to4_do_decode::~decoder_2to4_do_decode() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void decoder_2to4_do_decode::thread_dout() {
    if ((!esl_seteq<1,2,2>(val_V_read_fu_56_p2.read(), ap_const_lv2_3) && 
         !esl_seteq<1,2,2>(val_V_read_fu_56_p2.read(), ap_const_lv2_2) && 
         !esl_seteq<1,2,2>(val_V_read_fu_56_p2.read(), ap_const_lv2_1) && 
         !esl_seteq<1,2,2>(val_V_read_fu_56_p2.read(), ap_const_lv2_0))) {
        dout = ap_const_lv4_0;
    } else if (esl_seteq<1,2,2>(val_V_read_fu_56_p2.read(), ap_const_lv2_0)) {
        dout = ap_const_lv4_1;
    } else if (esl_seteq<1,2,2>(val_V_read_fu_56_p2.read(), ap_const_lv2_1)) {
        dout = ap_const_lv4_2;
    } else if (esl_seteq<1,2,2>(val_V_read_fu_56_p2.read(), ap_const_lv2_2)) {
        dout = ap_const_lv4_4;
    } else if (esl_seteq<1,2,2>(val_V_read_fu_56_p2.read(), ap_const_lv2_3)) {
        dout = ap_const_lv4_8;
    } else {
        dout = "XXXX";
    }
}

void decoder_2to4_do_decode::thread_dout_ap_vld() {
    if ((esl_seteq<1,2,2>(val_V_read_fu_56_p2.read(), ap_const_lv2_3) || 
         esl_seteq<1,2,2>(val_V_read_fu_56_p2.read(), ap_const_lv2_2) || 
         esl_seteq<1,2,2>(val_V_read_fu_56_p2.read(), ap_const_lv2_1) || 
         esl_seteq<1,2,2>(val_V_read_fu_56_p2.read(), ap_const_lv2_0) || 
         (!esl_seteq<1,2,2>(val_V_read_fu_56_p2.read(), ap_const_lv2_3) && 
          !esl_seteq<1,2,2>(val_V_read_fu_56_p2.read(), ap_const_lv2_2) && 
          !esl_seteq<1,2,2>(val_V_read_fu_56_p2.read(), ap_const_lv2_1) && 
          !esl_seteq<1,2,2>(val_V_read_fu_56_p2.read(), ap_const_lv2_0)))) {
        dout_ap_vld = ap_const_logic_1;
    } else {
        dout_ap_vld = ap_const_logic_0;
    }
}

void decoder_2to4_do_decode::thread_val_V_read_fu_56_p2() {
    val_V_read_fu_56_p2 = din.read();
}

}

