-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2015.4
-- Copyright (C) 2015 Xilinx Inc. All rights reserved.
-- 
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.std_logic_arith.all;
use IEEE.std_logic_unsigned.all;

entity alu_top is
    port (
        A : in  std_logic_vector(4 - 1 downto 0);
        B : in  std_logic_vector(4 - 1 downto 0);
        op_code : in  std_logic_vector(3 - 1 downto 0);
        result : out  std_logic_vector(4 - 1 downto 0);
        carry_borrow : out  std_logic
    );

-- attributes begin
-- attributes end
end entity;

architecture behav of alu_top is
    component ALU is
        port (
            A : in  std_logic_vector(4 - 1 downto 0);
            B : in  std_logic_vector(4 - 1 downto 0);
            op_code : in  std_logic_vector(3 - 1 downto 0);
            result : out  std_logic_vector(4 - 1 downto 0);
            carry_borrow : out  std_logic
        );
    end component;


begin
    ALU_U  : component ALU
        port map (
            A => A,
            B => B,
            op_code => op_code,
            result => result,
            carry_borrow => carry_borrow
        );

end architecture;

