// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

`timescale 1 ns / 1 ps
module alu_top (
A,
B,
op_code,
result,
carry_borrow
);

input [4 - 1:0] A ;
input [4 - 1:0] B ;
input [3 - 1:0] op_code ;
output [4 - 1:0] result ;
output carry_borrow ;




ALU ALU_U(
    .A(A),
    .B(B),
    .op_code(op_code),
    .result(result),
    .carry_borrow(carry_borrow)
);

endmodule
