-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2015.4
-- Copyright (C) 2015 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity counter_4bit_process is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    pe : IN STD_LOGIC;
    ud : IN STD_LOGIC;
    bd : IN STD_LOGIC;
    p : IN STD_LOGIC_VECTOR (3 downto 0);
    q : OUT STD_LOGIC_VECTOR (3 downto 0);
    q_ap_vld : OUT STD_LOGIC;
    count_i : IN STD_LOGIC_VECTOR (3 downto 0);
    count_o : OUT STD_LOGIC_VECTOR (3 downto 0);
    count_o_ap_vld : OUT STD_LOGIC );
end;


architecture behav of counter_4bit_process is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";

    signal tmp_read_fu_66_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st1_fsm_0 : STD_LOGIC;
    signal ap_sig_bdd_24 : BOOLEAN;
    signal grp_fu_115_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_read_fu_86_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_read_fu_92_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_129_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_135_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_122_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_4_fu_141_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);


begin




    -- the next state (ap_NS_fsm) of the state machine. --
    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                ap_NS_fsm <= ap_ST_st1_fsm_0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm <= ap_ST_st1_fsm_0;
        ap_sig_bdd_24 <= (ap_ST_st1_fsm_0(0 downto 0) = ap_const_lv1_1);

    -- ap_sig_cseq_ST_st1_fsm_0 assign process. --
    ap_sig_cseq_ST_st1_fsm_0_assign_proc : process(ap_sig_bdd_24)
    begin
        if (ap_sig_bdd_24) then 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_0;
        end if; 
    end process;


    -- count_o assign process. --
    count_o_assign_proc : process(p, tmp_read_fu_66_p2, ap_sig_cseq_ST_st1_fsm_0, grp_fu_115_p2, tmp_1_read_fu_86_p2, tmp_2_read_fu_92_p2, tmp_7_fu_129_p2, tmp_6_fu_135_p2, grp_fu_122_p2, tmp_4_fu_141_p2)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((tmp_read_fu_66_p2 = ap_const_lv1_0)) and not((ap_const_lv1_0 = tmp_2_read_fu_92_p2)) and not((ap_const_lv1_0 = tmp_1_read_fu_86_p2)) and not((ap_const_lv1_0 = tmp_4_fu_141_p2)))) then 
            count_o <= ap_const_lv4_F;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((tmp_read_fu_66_p2 = ap_const_lv1_0)) and (ap_const_lv1_0 = tmp_2_read_fu_92_p2) and not((ap_const_lv1_0 = tmp_1_read_fu_86_p2)) and not((ap_const_lv1_0 = tmp_4_fu_141_p2)))) then 
            count_o <= ap_const_lv4_9;
        elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((tmp_read_fu_66_p2 = ap_const_lv1_0)) and (ap_const_lv1_0 = tmp_2_read_fu_92_p2) and not((ap_const_lv1_0 = tmp_1_read_fu_86_p2)) and (ap_const_lv1_0 = tmp_4_fu_141_p2)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((tmp_read_fu_66_p2 = ap_const_lv1_0)) and not((ap_const_lv1_0 = tmp_2_read_fu_92_p2)) and not((ap_const_lv1_0 = tmp_1_read_fu_86_p2)) and (ap_const_lv1_0 = tmp_4_fu_141_p2)))) then 
            count_o <= grp_fu_122_p2;
        elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((tmp_read_fu_66_p2 = ap_const_lv1_0)) and (ap_const_lv1_0 = tmp_1_read_fu_86_p2) and (ap_const_lv1_0 = tmp_2_read_fu_92_p2) and not((ap_const_lv1_0 = tmp_7_fu_129_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((tmp_read_fu_66_p2 = ap_const_lv1_0)) and (ap_const_lv1_0 = tmp_1_read_fu_86_p2) and not((ap_const_lv1_0 = tmp_2_read_fu_92_p2)) and not((ap_const_lv1_0 = tmp_6_fu_135_p2))))) then 
            count_o <= ap_const_lv4_0;
        elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((tmp_read_fu_66_p2 = ap_const_lv1_0)) and (ap_const_lv1_0 = tmp_1_read_fu_86_p2) and (ap_const_lv1_0 = tmp_2_read_fu_92_p2) and (ap_const_lv1_0 = tmp_7_fu_129_p2)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((tmp_read_fu_66_p2 = ap_const_lv1_0)) and (ap_const_lv1_0 = tmp_1_read_fu_86_p2) and not((ap_const_lv1_0 = tmp_2_read_fu_92_p2)) and (ap_const_lv1_0 = tmp_6_fu_135_p2)))) then 
            count_o <= grp_fu_115_p2;
        elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (tmp_read_fu_66_p2 = ap_const_lv1_0))) then 
            count_o <= p;
        else 
            count_o <= "XXXX";
        end if; 
    end process;


    -- count_o_ap_vld assign process. --
    count_o_ap_vld_assign_proc : process(tmp_read_fu_66_p2, ap_sig_cseq_ST_st1_fsm_0, tmp_1_read_fu_86_p2, tmp_2_read_fu_92_p2, tmp_7_fu_129_p2, tmp_6_fu_135_p2, tmp_4_fu_141_p2)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and (tmp_read_fu_66_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((tmp_read_fu_66_p2 = ap_const_lv1_0)) and (ap_const_lv1_0 = tmp_1_read_fu_86_p2) and (ap_const_lv1_0 = tmp_2_read_fu_92_p2) and (ap_const_lv1_0 = tmp_7_fu_129_p2)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((tmp_read_fu_66_p2 = ap_const_lv1_0)) and (ap_const_lv1_0 = tmp_1_read_fu_86_p2) and (ap_const_lv1_0 = tmp_2_read_fu_92_p2) and not((ap_const_lv1_0 = tmp_7_fu_129_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((tmp_read_fu_66_p2 = ap_const_lv1_0)) and (ap_const_lv1_0 = tmp_1_read_fu_86_p2) and not((ap_const_lv1_0 = tmp_2_read_fu_92_p2)) and (ap_const_lv1_0 = tmp_6_fu_135_p2)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((tmp_read_fu_66_p2 = ap_const_lv1_0)) and (ap_const_lv1_0 = tmp_1_read_fu_86_p2) and not((ap_const_lv1_0 = tmp_2_read_fu_92_p2)) and not((ap_const_lv1_0 = tmp_6_fu_135_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((tmp_read_fu_66_p2 = ap_const_lv1_0)) and (ap_const_lv1_0 = tmp_2_read_fu_92_p2) and not((ap_const_lv1_0 = tmp_1_read_fu_86_p2)) and (ap_const_lv1_0 = tmp_4_fu_141_p2)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((tmp_read_fu_66_p2 = ap_const_lv1_0)) and (ap_const_lv1_0 = tmp_2_read_fu_92_p2) and not((ap_const_lv1_0 = tmp_1_read_fu_86_p2)) and not((ap_const_lv1_0 = tmp_4_fu_141_p2))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((tmp_read_fu_66_p2 = ap_const_lv1_0)) and not((ap_const_lv1_0 = tmp_2_read_fu_92_p2)) and not((ap_const_lv1_0 = tmp_1_read_fu_86_p2)) and (ap_const_lv1_0 = tmp_4_fu_141_p2)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((tmp_read_fu_66_p2 = ap_const_lv1_0)) and not((ap_const_lv1_0 = tmp_2_read_fu_92_p2)) and not((ap_const_lv1_0 = tmp_1_read_fu_86_p2)) and not((ap_const_lv1_0 = tmp_4_fu_141_p2))))) then 
            count_o_ap_vld <= ap_const_logic_1;
        else 
            count_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_115_p2 <= std_logic_vector(unsigned(count_i) + unsigned(ap_const_lv4_1));
    grp_fu_122_p2 <= std_logic_vector(unsigned(count_i) + unsigned(ap_const_lv4_F));
    q <= count_i;

    -- q_ap_vld assign process. --
    q_ap_vld_assign_proc : process(ap_sig_cseq_ST_st1_fsm_0)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0)) then 
            q_ap_vld <= ap_const_logic_1;
        else 
            q_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_read_fu_86_p2 <= (0=>ud, others=>'-');
    tmp_2_read_fu_92_p2 <= (0=>bd, others=>'-');
    tmp_4_fu_141_p2 <= "1" when (count_i = ap_const_lv4_0) else "0";
    tmp_6_fu_135_p2 <= "1" when (count_i = ap_const_lv4_F) else "0";
    tmp_7_fu_129_p2 <= "1" when (count_i = ap_const_lv4_9) else "0";
    tmp_read_fu_66_p2 <= (0=>pe, others=>'-');
end behav;
