// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mux_4to1,hls_ip_2015_4,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.877000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=1}" *)

module mux_4to1 (
        in0,
        in1,
        in2,
        in3,
        sel,
        out_r
);

parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;

input   in0;
input   in1;
input   in2;
input   in3;
input  [1:0] sel;
output   out_r;

wire    stg_11_mux_4to1_process_mux_fu_50_in0;
wire    stg_11_mux_4to1_process_mux_fu_50_in1;
wire    stg_11_mux_4to1_process_mux_fu_50_in2;
wire    stg_11_mux_4to1_process_mux_fu_50_in3;
wire   [1:0] stg_11_mux_4to1_process_mux_fu_50_sel;
wire    stg_11_mux_4to1_process_mux_fu_50_out_r;
wire    stg_11_mux_4to1_process_mux_fu_50_out_r_ap_vld;
wire   [0:0] mux_4to1_ssdm_thread_M_proc_load_fu_66_p1;


mux_4to1_process_mux stg_11_mux_4to1_process_mux_fu_50(
    .in0( stg_11_mux_4to1_process_mux_fu_50_in0 ),
    .in1( stg_11_mux_4to1_process_mux_fu_50_in1 ),
    .in2( stg_11_mux_4to1_process_mux_fu_50_in2 ),
    .in3( stg_11_mux_4to1_process_mux_fu_50_in3 ),
    .sel( stg_11_mux_4to1_process_mux_fu_50_sel ),
    .out_r( stg_11_mux_4to1_process_mux_fu_50_out_r ),
    .out_r_ap_vld( stg_11_mux_4to1_process_mux_fu_50_out_r_ap_vld )
);



assign mux_4to1_ssdm_thread_M_proc_load_fu_66_p1 = ap_const_lv1_0;

assign out_r = stg_11_mux_4to1_process_mux_fu_50_out_r;

assign stg_11_mux_4to1_process_mux_fu_50_in0 = in0;

assign stg_11_mux_4to1_process_mux_fu_50_in1 = in1;

assign stg_11_mux_4to1_process_mux_fu_50_in2 = in2;

assign stg_11_mux_4to1_process_mux_fu_50_in3 = in3;

assign stg_11_mux_4to1_process_mux_fu_50_sel = sel;


endmodule //mux_4to1

