// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _mux_4to1_HH_
#define _mux_4to1_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "mux_4to1_process_mux.h"

namespace ap_rtl {

struct mux_4to1 : public sc_module {
    // Port declarations 6
    sc_in< sc_logic > in0;
    sc_in< sc_logic > in1;
    sc_in< sc_logic > in2;
    sc_in< sc_logic > in3;
    sc_in< sc_lv<2> > sel;
    sc_out< sc_logic > out_r;
    // Internal clock declarations for combination SystemC design. 
    sc_clock ap_sc_inter_clock;


    // Module declarations
    mux_4to1(sc_module_name name);
    SC_HAS_PROCESS(mux_4to1);

    ~mux_4to1();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    mux_4to1_process_mux* stg_11_mux_4to1_process_mux_fu_50;
    sc_signal< sc_logic > stg_11_mux_4to1_process_mux_fu_50_in0;
    sc_signal< sc_logic > stg_11_mux_4to1_process_mux_fu_50_in1;
    sc_signal< sc_logic > stg_11_mux_4to1_process_mux_fu_50_in2;
    sc_signal< sc_logic > stg_11_mux_4to1_process_mux_fu_50_in3;
    sc_signal< sc_lv<2> > stg_11_mux_4to1_process_mux_fu_50_sel;
    sc_signal< sc_logic > stg_11_mux_4to1_process_mux_fu_50_out_r;
    sc_signal< sc_logic > stg_11_mux_4to1_process_mux_fu_50_out_r_ap_vld;
    sc_signal< sc_lv<1> > mux_4to1_ssdm_thread_M_proc_load_fu_66_p1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_mux_4to1_ssdm_thread_M_proc_load_fu_66_p1();
    void thread_out_r();
    void thread_stg_11_mux_4to1_process_mux_fu_50_in0();
    void thread_stg_11_mux_4to1_process_mux_fu_50_in1();
    void thread_stg_11_mux_4to1_process_mux_fu_50_in2();
    void thread_stg_11_mux_4to1_process_mux_fu_50_in3();
    void thread_stg_11_mux_4to1_process_mux_fu_50_sel();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
