// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _mux_4to1_process_mux_HH_
#define _mux_4to1_process_mux_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct mux_4to1_process_mux : public sc_module {
    // Port declarations 7
    sc_in< sc_logic > in0;
    sc_in< sc_logic > in1;
    sc_in< sc_logic > in2;
    sc_in< sc_logic > in3;
    sc_in< sc_lv<2> > sel;
    sc_out< sc_logic > out_r;
    sc_out< sc_logic > out_r_ap_vld;


    // Module declarations
    mux_4to1_process_mux(sc_module_name name);
    SC_HAS_PROCESS(mux_4to1_process_mux);

    ~mux_4to1_process_mux();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<2> > val_V_read_fu_66_p2;
    static const bool ap_true;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_logic ap_const_logic_0;
    static const sc_logic ap_const_logic_1;
    // Thread declarations
    void thread_out_r();
    void thread_out_r_ap_vld();
    void thread_val_V_read_fu_66_p2();
};

}

using namespace ap_rtl;

#endif
