// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ALU_perform_operation (
        A,
        B,
        op_code,
        result,
        result_ap_vld,
        carry_borrow,
        carry_borrow_ap_vld
);

parameter    ap_true = 1'b1;
parameter    ap_const_lv3_7 = 3'b111;
parameter    ap_const_lv3_6 = 3'b110;
parameter    ap_const_lv3_5 = 3'b101;
parameter    ap_const_lv3_4 = 3'b100;
parameter    ap_const_lv3_3 = 3'b11;
parameter    ap_const_lv3_2 = 3'b10;
parameter    ap_const_lv3_1 = 3'b1;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_lv4_F = 4'b1111;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_const_lv32_4 = 32'b100;

input  [3:0] A;
input  [3:0] B;
input  [2:0] op_code;
output  [3:0] result;
output   result_ap_vld;
output   carry_borrow;
output   carry_borrow_ap_vld;

wire   [3:0] r_V_7_fu_177_p2;
reg   [3:0] v_V_phi_fu_119_p18;
wire   [2:0] val_V_read_fu_84_p2;
wire   [3:0] res_V_6_fu_184_p2;
wire   [3:0] r_V_6_fu_191_p2;
wire   [3:0] grp_fu_170_p2;
wire   [3:0] res_V_3_fu_198_p2;
wire   [3:0] res_V_2_fu_212_p2;
wire   [3:0] res_V_1_fu_226_p2;
wire   [3:0] res_V_fu_240_p2;
reg   [0:0] v_phi_fu_144_p18;
wire   [0:0] carry_3_fu_205_p2;
wire   [0:0] carry_2_fu_219_p2;
wire   [0:0] carry_1_fu_233_p2;
wire   [4:0] rhs_V_fu_251_p1;
wire   [4:0] lhs_V_fu_247_p1;
wire   [4:0] r_V_fu_255_p2;




assign carry_borrow_ap_vld = ap_const_logic_1;

assign result_ap_vld = ap_const_logic_1;

always @ (r_V_7_fu_177_p2 or val_V_read_fu_84_p2 or res_V_6_fu_184_p2 or r_V_6_fu_191_p2 or grp_fu_170_p2 or res_V_3_fu_198_p2 or res_V_2_fu_212_p2 or res_V_1_fu_226_p2 or res_V_fu_240_p2) begin
    if ((~(val_V_read_fu_84_p2 == ap_const_lv3_7) & ~(val_V_read_fu_84_p2 == ap_const_lv3_6) & ~(val_V_read_fu_84_p2 == ap_const_lv3_5) & ~(val_V_read_fu_84_p2 == ap_const_lv3_4) & ~(val_V_read_fu_84_p2 == ap_const_lv3_3) & ~(val_V_read_fu_84_p2 == ap_const_lv3_2) & ~(val_V_read_fu_84_p2 == ap_const_lv3_1) & ~(val_V_read_fu_84_p2 == ap_const_lv3_0))) begin
        v_V_phi_fu_119_p18 = ap_const_lv4_0;
    end else if ((val_V_read_fu_84_p2 == ap_const_lv3_0)) begin
        v_V_phi_fu_119_p18 = res_V_fu_240_p2;
    end else if ((val_V_read_fu_84_p2 == ap_const_lv3_1)) begin
        v_V_phi_fu_119_p18 = res_V_1_fu_226_p2;
    end else if ((val_V_read_fu_84_p2 == ap_const_lv3_2)) begin
        v_V_phi_fu_119_p18 = res_V_2_fu_212_p2;
    end else if ((val_V_read_fu_84_p2 == ap_const_lv3_3)) begin
        v_V_phi_fu_119_p18 = res_V_3_fu_198_p2;
    end else if ((val_V_read_fu_84_p2 == ap_const_lv3_4)) begin
        v_V_phi_fu_119_p18 = grp_fu_170_p2;
    end else if ((val_V_read_fu_84_p2 == ap_const_lv3_5)) begin
        v_V_phi_fu_119_p18 = r_V_6_fu_191_p2;
    end else if ((val_V_read_fu_84_p2 == ap_const_lv3_6)) begin
        v_V_phi_fu_119_p18 = res_V_6_fu_184_p2;
    end else if ((val_V_read_fu_84_p2 == ap_const_lv3_7)) begin
        v_V_phi_fu_119_p18 = r_V_7_fu_177_p2;
    end else begin
        v_V_phi_fu_119_p18 = 'bx;
    end
end

always @ (val_V_read_fu_84_p2 or carry_3_fu_205_p2 or carry_2_fu_219_p2 or carry_1_fu_233_p2 or r_V_fu_255_p2) begin
    if ((val_V_read_fu_84_p2 == ap_const_lv3_0)) begin
        v_phi_fu_144_p18 = r_V_fu_255_p2[ap_const_lv32_4];
    end else if ((val_V_read_fu_84_p2 == ap_const_lv3_1)) begin
        v_phi_fu_144_p18 = carry_1_fu_233_p2;
    end else if ((val_V_read_fu_84_p2 == ap_const_lv3_2)) begin
        v_phi_fu_144_p18 = carry_2_fu_219_p2;
    end else if ((val_V_read_fu_84_p2 == ap_const_lv3_3)) begin
        v_phi_fu_144_p18 = carry_3_fu_205_p2;
    end else if (((val_V_read_fu_84_p2 == ap_const_lv3_7) | (val_V_read_fu_84_p2 == ap_const_lv3_6) | (val_V_read_fu_84_p2 == ap_const_lv3_5) | (val_V_read_fu_84_p2 == ap_const_lv3_4) | (~(val_V_read_fu_84_p2 == ap_const_lv3_7) & ~(val_V_read_fu_84_p2 == ap_const_lv3_6) & ~(val_V_read_fu_84_p2 == ap_const_lv3_5) & ~(val_V_read_fu_84_p2 == ap_const_lv3_4) & ~(val_V_read_fu_84_p2 == ap_const_lv3_3) & ~(val_V_read_fu_84_p2 == ap_const_lv3_2) & ~(val_V_read_fu_84_p2 == ap_const_lv3_1) & ~(val_V_read_fu_84_p2 == ap_const_lv3_0)))) begin
        v_phi_fu_144_p18 = ap_const_lv1_0;
    end else begin
        v_phi_fu_144_p18 = 'bx;
    end
end

assign carry_1_fu_233_p2 = (A < B? 1'b1: 1'b0);

assign carry_2_fu_219_p2 = (A == ap_const_lv4_F? 1'b1: 1'b0);

assign carry_3_fu_205_p2 = (A == ap_const_lv4_0? 1'b1: 1'b0);

assign carry_borrow = v_phi_fu_144_p18;

assign grp_fu_170_p2 = (B & A);

assign lhs_V_fu_247_p1 = A;

assign r_V_6_fu_191_p2 = (B | A);

assign r_V_7_fu_177_p2 = (B ^ A);

assign r_V_fu_255_p2 = (rhs_V_fu_251_p1 + lhs_V_fu_247_p1);

assign res_V_1_fu_226_p2 = (A - B);

assign res_V_2_fu_212_p2 = (A + ap_const_lv4_1);

assign res_V_3_fu_198_p2 = ($signed(A) + $signed(ap_const_lv4_F));

assign res_V_6_fu_184_p2 = (grp_fu_170_p2 ^ ap_const_lv4_F);

assign res_V_fu_240_p2 = (B + A);

assign result = v_V_phi_fu_119_p18;

assign rhs_V_fu_251_p1 = B;

assign val_V_read_fu_84_p2 = op_code;


endmodule //ALU_perform_operation

