# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2015.4
# Copyright (C) 2015 Xilinx Inc. All rights reserved.
# 
# ==============================================================

#
# Settings for Vivado implementation flow
#
set top_module ALU
set language vhdl
set family zynq
set device xc7z020
set package clg484
set speed -1
set clock ""
set fsm_ext "off"

# For customizing the implementation flow
set add_io_buffers false ;# true|false

set src_files [list \
    ALU.v \
    ALU_perform_operation.v \
]

set pcore_syn 1
set pcore_lang verilog
